export type OrganId =
  | "heart"
  | "brain"
  | "lungs"
  | "liver"
  | "kidneys"
  | "eyeball"
  | "intestine"
  | "small-intestine"
  | "large-intestine"
  | "pelvis"
  | "knee-joint"
  | "pancreas"
  | "skin"
  | "stomach"
  | "esophagus"
  | "spleen"
  | "gallbladder"
  | "bladder"
  | "trachea"
  | "larynx"
  | "main-bronchus"
  | "appendix"
  | "tongue"
  | "ear"
  | "adrenal"
  | "diaphragm"
  | "thymus"
  | "spinal-cord"
  | "uterus"
  | "ovary"
  | "prostate"
  | "ureter"
  | "fallopian-tubes"
  | "mammary-glands"
  | "palatine-tonsils"
  | "skeleton"
  | "shoulder-joint"
  | "elbow-joint"
  | "hip-joint"
  | "ankle-foot"
  | "thyroid"
  | "pituitary"
  | "parathyroids"
  | "testis-epididymis"
  | "salivary-glands"
  | "pharynx"
  | "lymph-node"
  | "blood-vessels"
  | "placenta"
  | "urethra"
  | "muscular-system"
  | "skull"
  | "spine"
  | "hand-wrist"
  | "rotator-cuff"
  | "brachial-plexus"
  | "brainstem-cerebellum"
  | "coronary-circulation"
  | "sciatic-nerve"
  | "cranial-nerves"
  | "pelvic-floor-perineum"
  | "inguinal-canal"
  | "tmj"
  | "intervertebral-discs"
  | "median-nerve"
  | "ulnar-nerve"
  | "radial-nerve"
  | "typical-vertebrae"
  | "lymphatic-system"
  | "teeth"
  | "nose";

export type Hotspot = {
  id: string;
  label: string;
  detail: string;
  position: [number, number, number];
  color: string;
};

export type Organ = {
  id: OrganId;
  name: string;
  scientificName: string;
  system: string;
  model: string;
  icon: string;
  accent: string;
  /** Optional viewer-only framing multiplier for models whose source mesh
   *  includes long surrounding anatomy around a small structure of interest. */
  viewScale?: number;
  /** Optional marker diameter for dense models; defaults to the viewer-wide
   *  size when omitted. */
  hotspotSize?: number;
  description: string;
  poetic: string;
  size: string;
  weight: string;
  location: string;
  function: string;
  dailyFact: string;
  medical: string;
  bloodSupply: string;
  /** A single memorable line, surfaced as the "Did you know" note. */
  funFact: string;
  hotspots: Hotspot[];
  /** Whether `/anatomy/<id>/*.webp` illustrations exist. Organs without them
   *  fall back to the accent glyph rather than a broken image. */
  illustrated: boolean;
};

export const organs: Organ[] = [
  {
    id: "heart",
    name: "心脏",
    scientificName: "Cor",
    system: "心血管系统",
    model: "/models/heart.glb",
    icon: "♥",
    accent: "#ee7c6a",
    description: "一个肌性器官，推动血液流遍全身，为每个细胞输送氧气和营养。",
    poetic: "不知疲倦的泵",
    size: "约等于你自己的拳头",
    weight: "250–350 克",
    location: "胸骨后方，略偏左",
    function: "推动含氧血液循环",
    dailyFact: "每天跳动约 10 万次",
    medical: "它的电节律协调着每一次心跳。",
    bloodSupply: "左、右冠状动脉",
    funFact: "人的一生中它约跳动 25 亿次，而且在出生之前就已经开始跳动。",
    illustrated: true,
    hotspots: [
      { id: "aorta", label: "主动脉", detail: "全身最大的动脉", position: [-0.35, 1.65, 0.55], color: "#ee7c6a" },
      { id: "left-atrium", label: "左心房", detail: "接收含氧血液", position: [0.82, 0.65, 0.5], color: "#f2a33b" },
      { id: "right-atrium", label: "右心房", detail: "接收静脉血", position: [-0.9, 0.35, 0.55], color: "#6393d8" },
      { id: "left-ventricle", label: "左心室", detail: "将血液泵向全身", position: [0.7, -0.75, 0.65], color: "#f2a33b" },
      { id: "right-ventricle", label: "右心室", detail: "将血液泵向肺部", position: [-0.65, -0.68, 0.66], color: "#ee7c6a" },
      { id: "mitral", label: "二尖瓣", detail: "防止血液回流", position: [0.18, -1.35, 0.48], color: "#d89bc4" },
    ],
  },
  {
    id: "brain",
    name: "大脑",
    scientificName: "Encephalon",
    system: "神经系统",
    model: "/models/brain.glb",
    icon: "◉",
    accent: "#c58696",
    description: "人体的指挥中心，整合感觉、记忆、情绪与精确的运动。",
    poetic: "内在宇宙",
    size: "约等于两只紧握的拳头",
    weight: "1.3–1.4 千克",
    location: "受颅骨保护",
    function: "处理并协调信号",
    dailyFact: "消耗全身约 20% 的能量",
    medical: "数十亿神经元通过电信号与化学信号相互通信。",
    bloodSupply: "颈内动脉与椎动脉",
    funFact: "大脑本身没有痛觉感受器——头痛其实来自它周围的组织。",
    illustrated: true,
    hotspots: [
      { id: "frontal", label: "额叶", detail: "计划与运动", position: [-0.7, 0.65, 0.8], color: "#ee7c6a" },
      { id: "parietal", label: "顶叶", detail: "感觉整合", position: [0.15, 1.1, 0.65], color: "#f2a33b" },
      { id: "temporal", label: "颞叶", detail: "记忆与听觉", position: [0.75, -0.1, 0.82], color: "#6393d8" },
      { id: "cerebellum", label: "小脑", detail: "平衡与协调", position: [0.72, -0.9, 0.55], color: "#d89bc4" },
    ],
  },
  {
    id: "lungs",
    name: "肺",
    scientificName: "Pulmones",
    system: "呼吸系统",
    model: "/models/lungs.glb",
    icon: "◍",
    accent: "#dd8f8b",
    description: "成对的器官，吸入空气，在广阔而脆弱的表面上以氧气交换二氧化碳。",
    poetic: "生命的气息",
    size: "每侧约 25 厘米高",
    weight: "双肺共约 1 千克",
    location: "心脏两侧，胸腔之内",
    function: "以氧气交换二氧化碳",
    dailyFact: "每天通气约 11,000 升",
    medical: "肺泡把相当于一个网球场大小的交换表面折叠进胸腔。",
    bloodSupply: "肺动脉与支气管动脉",
    funFact: "右肺有三叶，左肺只有两叶——为心脏留出了位置。",
    illustrated: true,
    hotspots: [
      { id: "trachea", label: "气管", detail: "将空气输送入肺", position: [0, 1.6, 0.2], color: "#6393d8" },
      { id: "right-lung", label: "右肺", detail: "分为三叶", position: [-1.2, 0.1, 0.7], color: "#ee7c6a" },
      { id: "left-lung", label: "左肺", detail: "两叶，为心脏留出空间", position: [1.2, 0.1, 0.7], color: "#f2a33b" },
      { id: "bronchus", label: "支气管", detail: "分支状气道", position: [-0.03, 0.3, 0.35], color: "#d89bc4" },
      { id: "base", label: "肺底", detail: "坐落在膈肌上", position: [-1.14, -1.2, 1], color: "#7fa88a" },
    ],
  },
  {
    id: "liver",
    name: "肝脏",
    scientificName: "Hepar",
    system: "消化系统",
    model: "/models/liver.glb",
    icon: "≈",
    accent: "#b86858",
    description: "卓越的代谢器官，过滤血液、处理营养物质并生成胆汁。",
    poetic: "沉默的炼金术士",
    size: "约一个橄榄球大小",
    weight: "1.4–1.6 千克",
    location: "右上腹",
    function: "代谢、解毒与分泌胆汁",
    dailyFact: "执行 500 多种功能",
    medical: "失去大量组织后仍能再生。",
    bloodSupply: "肝动脉与门静脉",
    funFact: "它是唯一能从一小部分组织再生回完整大小的人体器官。",
    illustrated: true,
    hotspots: [
      { id: "right-lobe", label: "右叶", detail: "最大的肝叶", position: [-0.75, 0.35, 0.75], color: "#ee7c6a" },
      { id: "left-lobe", label: "左叶", detail: "跨越中线", position: [0.85, 0.25, 0.75], color: "#f2a33b" },
      { id: "portal", label: "门静脉", detail: "富含营养的入肝血流", position: [0.1, -0.3, 0.82], color: "#6393d8" },
    ],
  },
  {
    id: "kidneys",
    name: "肾脏",
    scientificName: "Renes",
    system: "泌尿系统",
    model: "/models/kidneys.glb",
    icon: "∞",
    accent: "#c96963",
    description: "成对的过滤器官，维持体液、电解质与血压的平衡，并清除代谢废物。",
    poetic: "大师级过滤器",
    size: "每个约一只鼠标大小",
    weight: "每个 120–170 克",
    location: "脊柱两侧、肋骨下方",
    function: "过滤血液并生成尿液",
    dailyFact: "每天过滤约 180 升液体",
    medical: "肾单位精细调节血液的化学成分。",
    bloodSupply: "肾动脉",
    funFact: "过滤出的物质几乎都会被重吸收——最终只有约 1–2 升以尿液排出体外。",
    illustrated: true,
    hotspots: [
      { id: "cortex", label: "肾皮质", detail: "外层过滤结构", position: [-0.9, 0.55, 0.7], color: "#ee7c6a" },
      { id: "medulla", label: "肾髓质", detail: "浓缩尿液", position: [0.85, 0.2, 0.7], color: "#f2a33b" },
      { id: "ureter", label: "输尿管", detail: "输送尿液", position: [0.4, -1.1, 0.5], color: "#6393d8" },
    ],
  },
  {
    id: "eyeball",
    name: "眼",
    scientificName: "Oculus",
    system: "感觉系统",
    model: "/models/eyeball.glb",
    icon: "⊙",
    accent: "#7294b9",
    description: "精密的感觉器官，将聚焦的光线转化为神经信号，被大脑解读为视觉。",
    poetic: "一扇由光构成的窗",
    size: "直径约 24 毫米",
    weight: "约 7.5 克",
    location: "骨性眼眶之内",
    function: "捕捉并聚焦光线",
    dailyFact: "每天进行数千次微小运动",
    medical: "视网膜是中枢神经系统的延伸。",
    bloodSupply: "眼动脉",
    funFact: "角膜完全不含血管，直接从空气中获取氧气。",
    illustrated: true,
    hotspots: [
      { id: "cornea", label: "角膜", detail: "透明的聚焦表面", position: [-0.94, 0.05, 1.47], color: "#6393d8" },
      { id: "iris", label: "虹膜", detail: "控制进光量", position: [-1.22, -0.53, 1.15], color: "#f2a33b" },
      { id: "optic", label: "视神经", detail: "传递视觉信号", position: [1.61, -0.18, 0.54], color: "#d89bc4" },
    ],
  },
  {
    id: "intestine",
    name: "肠道（整体）",
    scientificName: "Intestinum",
    system: "消化系统",
    model: "/models/intestine.glb",
    icon: "§",
    accent: "#d78b77",
    description: "曲折盘绕的消化管道，营养在此吸收，肠道菌群支持着全身健康。",
    poetic: "内在花园",
    size: "完全展开约 6–7 米",
    weight: "随内容物而变化",
    location: "腹部中下部",
    function: "消化与营养吸收",
    dailyFact: "栖息着数万亿微生物",
    medical: "它的表面积被皱襞、绒毛和微绒毛逐级放大。",
    bloodSupply: "肠系膜上、下动脉",
    funFact: "肠内壁每隔几天就自我更新一次——是全身更新最快的组织。",
    illustrated: true,
    hotspots: [
      { id: "duodenum", label: "十二指肠", detail: "小肠的第一段", position: [0.6, 0.8, 0.75], color: "#f2a33b" },
      { id: "jejunum", label: "空肠", detail: "主要的吸收区域", position: [-0.45, 0.1, 0.82], color: "#ee7c6a" },
      { id: "colon", label: "结肠", detail: "重吸收水分", position: [0.75, -0.55, 0.72], color: "#6393d8" },
    ],
  },
  {
    id: "small-intestine",
    name: "小肠",
    scientificName: "Intestinum tenue",
    system: "消化系统",
    model: "/models/small-intestine.glb",
    icon: "∿",
    accent: "#d98a72",
    description: "连接胃与大肠的细长消化管，由十二指肠、空肠和回肠组成，是食物消化与营养吸收的主要场所。",
    poetic: "营养进入身体的长廊",
    size: "成人通常长约 5–6 米",
    weight: "随内容物与蠕动状态变化",
    location: "腹腔中央，大部分被大肠环绕",
    function: "完成消化并吸收大多数营养物质",
    dailyFact: "持续通过分节运动与蠕动混合、推进食糜",
    medical: "绒毛和微绒毛显著扩大吸收面积；炎症、梗阻或吸收障碍会影响营养状态。",
    bloodSupply: "肠系膜上动脉及其分支",
    funFact: "小肠虽然直径比大肠小，却承担了绝大多数营养吸收工作。",
    illustrated: true,
    hotspots: [
      { id: "duodenum", label: "十二指肠", detail: "接收胃内容物、胆汁与胰液", position: [-0.45, 1.25, 0.25], color: "#f2a33b" },
      { id: "jejunum", label: "空肠", detail: "皱襞发达，是营养吸收的重要区域", position: [0.25, -0.05, 0.45], color: "#ee7c6a" },
      { id: "ileum", label: "回肠", detail: "吸收胆盐和维生素 B12 等物质", position: [0.15, -0.78, 0.55], color: "#6393d8" },
      { id: "terminal-ileum", label: "回肠末端", detail: "经回盲瓣与大肠相接", position: [-0.68, -1.08, 0.05], color: "#d89bc4" },
    ],
  },
  {
    id: "large-intestine",
    name: "大肠",
    scientificName: "Intestinum crassum",
    system: "消化系统",
    model: "/models/large-intestine.glb",
    icon: "⌁",
    accent: "#bd806d",
    description: "由盲肠、结肠、直肠等部分构成的消化道末段，主要回收水和电解质，并储存、形成和排出粪便。",
    poetic: "水分回收的最后一程",
    size: "成人通常长约 1.5 米",
    weight: "随内容物变化",
    location: "腹腔外围环绕小肠，并向盆腔延续",
    function: "吸收水分、形成并排出粪便",
    dailyFact: "结肠菌群会发酵未被小肠吸收的食物成分",
    medical: "憩室、炎症、息肉和肿瘤都可能影响大肠；筛查有助于发现癌前病变。",
    bloodSupply: "肠系膜上动脉与肠系膜下动脉",
    funFact: "大肠名字里的“大”指管径更粗，而不是长度更长。",
    illustrated: true,
    hotspotSize: 24,
    hotspots: [
      { id: "ascending-colon", label: "升结肠", detail: "沿右侧腹部向上延伸", position: [-1.25, 0.65, 0.45], color: "#ee7c6a" },
      { id: "hepatic-flexure", label: "结肠肝曲", detail: "升结肠转为横结肠的右上腹弯曲", position: [-1.07, 1.17, 0.35], color: "#c9956a" },
      { id: "transverse-colon", label: "横结肠", detail: "横过上腹部，活动度相对较大", position: [0.05, 1.25, 0.75], color: "#f2a33b" },
      { id: "splenic-flexure", label: "结肠脾曲", detail: "横结肠转为降结肠的左上腹弯曲", position: [1.13, 1.42, 0.45], color: "#b887a4" },
      { id: "descending-colon", label: "降结肠", detail: "沿左侧腹部向下延伸", position: [1.15, 0.2, 0.45], color: "#6393d8" },
      { id: "caecum", label: "盲肠", detail: "大肠起始处的袋状结构", position: [-1.15, -0.02, 0.5], color: "#7fa88a" },
      { id: "ileocecal-valve", label: "回盲瓣", detail: "调节回肠内容物进入大肠并减少反流", position: [-0.95, 0.23, 0.2], color: "#c58696" },
      { id: "sigmoid-colon", label: "乙状结肠", detail: "弯曲进入盆腔并连接直肠", position: [-0.05, -0.88, 0.45], color: "#d89bc4" },
      { id: "rectum", label: "直肠", detail: "暂时储存粪便并参与排便反射", position: [0.1, -1.25, -0.55], color: "#7fa88a" },
    ],
  },
  {
    id: "pelvis",
    name: "骨盆（女性参考）",
    scientificName: "Pelvis ossea feminina",
    system: "骨骼系统",
    model: "/models/pelvis.glb",
    icon: "⌵",
    accent: "#c6a57d",
    description: "由左右髋骨、骶骨和尾骨围成的骨性环，连接躯干与下肢，并保护盆腔器官；此模型采用女性参考标本。",
    poetic: "承上启下的骨性环",
    size: "成人横径约 25–30 厘米，个体差异明显",
    weight: "由多块骨骼共同构成",
    location: "躯干下端、双侧髋关节之间",
    function: "传递体重、稳定躯干并保护盆腔器官",
    dailyFact: "行走时骨盆会进行幅度很小但连续的旋转与倾斜",
    medical: "骨盆骨折可能伴随大出血和脏器损伤；女性骨盆形态也与分娩通道密切相关。",
    bloodSupply: "髂腰、臀上、臀下、闭孔等动脉分支",
    funFact: "骨盆不是一整块骨，而是由多块骨在关节和韧带处连接形成的环。",
    illustrated: true,
    hotspotSize: 26,
    hotspots: [
      { id: "sacrum", label: "骶骨", detail: "连接脊柱与骨盆的楔形骨", position: [0, 0.42, -0.55], color: "#d89bc4" },
      { id: "ilium-left", label: "左髂骨", detail: "构成骨盆宽大的上部", position: [1.2, 0.45, 0.45], color: "#ee7c6a" },
      { id: "ilium-right", label: "右髂骨", detail: "与骶骨形成骶髂关节", position: [-1.2, 0.45, 0.45], color: "#f2a33b" },
      { id: "pubis", label: "耻骨", detail: "在前方通过耻骨联合连接", position: [0, -0.65, 0.85], color: "#6393d8" },
      { id: "ischium", label: "坐骨", detail: "构成髋骨后下部，坐位时承受部分体重", position: [-0.94, -0.7, 0], color: "#c9956a" },
      { id: "acetabulum", label: "髋臼", detail: "容纳股骨头并形成髋关节", position: [1.48, -0.28, 0.38], color: "#b887a4" },
      { id: "coccyx", label: "尾骨", detail: "脊柱最下端的小骨群", position: [0, -0.35, -0.82], color: "#7fa88a" },
    ],
  },
  {
    id: "knee-joint",
    name: "膝关节（左侧参考）",
    scientificName: "Articulatio genus sinistra",
    system: "运动系统",
    model: "/models/knee-joint.glb",
    icon: "⋔",
    accent: "#c9a479",
    viewScale: 2.6,
    hotspotSize: 20,
    description: "由股骨、胫骨、髌骨及半月板等结构共同组成的大型负重关节；此模型展示女性左膝参考结构。",
    poetic: "行走中的承重铰链",
    size: "关节区高度约 10–12 厘米",
    weight: "骨、软骨、韧带和滑膜共同构成",
    location: "大腿与小腿之间",
    function: "屈伸、承重并在运动中维持稳定",
    dailyFact: "步行和上下楼时承受的瞬时载荷可超过体重",
    medical: "半月板、交叉韧带和关节软骨损伤是常见运动损伤，长期磨损可导致骨关节炎。",
    bloodSupply: "膝关节动脉网",
    funFact: "髌骨是人体最大的籽骨，能改善股四头肌伸膝时的力臂。",
    illustrated: true,
    hotspots: [
      { id: "femur", label: "股骨远端", detail: "以股骨髁参与关节面构成", position: [0, 0.35, 0.12], color: "#ee7c6a" },
      { id: "meniscus", label: "半月板", detail: "分散压力并改善关节面匹配", position: [-0.12, -0.2, -0.02], color: "#6393d8" },
      { id: "patella", label: "髌骨", detail: "保护关节前方并提高伸膝效率", position: [0.04, -0.02, 0.25], color: "#f2a33b" },
      { id: "articular-cartilage", label: "关节软骨", detail: "覆盖关节面，降低摩擦并分散冲击", position: [0.14, -0.1, -0.01], color: "#7fa88a" },
      { id: "cruciate-entheses", label: "交叉韧带附着区", detail: "前、后交叉韧带在髁间区的骨性附着位置", position: [-0.04, -0.07, -0.1], color: "#c58696" },
      { id: "tibia", label: "胫骨近端", detail: "承担来自股骨的大部分负荷", position: [-0.02, -0.48, 0.05], color: "#d89bc4" },
      { id: "fibula", label: "腓骨近端", detail: "位于小腿外侧，提供韧带附着点", position: [0.18, -0.55, -0.15], color: "#7fa88a" },
    ],
  },
  {
    id: "pancreas",
    name: "胰腺",
    scientificName: "Pancreas",
    system: "内分泌系统",
    model: "/models/pancreas.glb",
    icon: "◈",
    accent: "#c69a5e",
    description: "一腺两用：向肠道释放消化酶，同时分泌稳定血糖的激素。",
    poetic: "安静的调节者",
    size: "长约 15 厘米",
    weight: "70–100 克",
    location: "胃的后方，横过上腹部",
    function: "分泌消化酶与胰岛素",
    dailyFact: "每天产生约 1.5 升富含酶的胰液",
    medical: "胰岛释放胰岛素和胰高血糖素，维持血糖平衡。",
    bloodSupply: "脾动脉与胰十二指肠动脉",
    funFact: "只有约 2% 的组织负责分泌激素，其余都用于制造消化酶。",
    illustrated: true,
    hotspots: [
      { id: "head", label: "胰头", detail: "被十二指肠环抱", position: [-1.32, -0.36, 0.55], color: "#ee7c6a" },
      { id: "body", label: "胰体", detail: "横跨脊柱", position: [0.05, 0.25, 0.45], color: "#f2a33b" },
      { id: "tail", label: "胰尾", detail: "延伸至脾脏", position: [1.55, 0.3, 0.35], color: "#6393d8" },
      { id: "duct", label: "胰管", detail: "将消化酶排入肠道", position: [-0.61, 0.39, 0.5], color: "#d89bc4" },
    ],
  },
  {
    id: "skin",
    name: "皮肤",
    scientificName: "Integumentum",
    system: "体被系统",
    model: "/models/skin.glb",
    icon: "▦",
    accent: "#c99277",
    description: "人体最大的器官——一道活的屏障，感知触觉、锁住水分并调节体温。",
    poetic: "活的边界",
    size: "摊平约 2 平方米",
    weight: "3.5–5 千克",
    location: "覆盖全身",
    function: "保护、感知与散热",
    dailyFact: "每天脱落约 5 亿个细胞",
    medical: "表皮、真皮、皮下组织三层各有分工。",
    bloodSupply: "真皮血管丛",
    funFact: "一平方厘米的皮肤可容纳数百个汗腺和数米长的血管。",
    illustrated: true,
    hotspots: [
      { id: "epidermis", label: "表皮", detail: "外部的保护层", position: [-0.05, 0.88, 1.4], color: "#ee7c6a" },
      { id: "dermis", label: "真皮", detail: "神经、血管与腺体所在", position: [0.29, 0.05, 1.4], color: "#f2a33b" },
      { id: "hypodermis", label: "皮下组织", detail: "脂肪与保温层", position: [-0.39, -1.15, 1.4], color: "#6393d8" },
      { id: "follicle", label: "毛囊", detail: "固定每根毛发", position: [0.89, -0.44, 1.4], color: "#d89bc4" },
    ],
  },
  {
    id: "stomach",
    name: "胃",
    scientificName: "Gaster",
    system: "消化系统",
    model: "/models/stomach.glb",
    icon: "∪",
    accent: "#dd8a72",
    description: "J 形的肌性囊袋，通过蠕动、胃酸与消化酶把食物搅拌成食糜，再分批送入小肠。",
    poetic: "消化的熔炉",
    size: "完全舒张时长约 25 厘米",
    weight: "空腹时约 150–200 克",
    location: "左上腹，肋弓下方",
    function: "储存并初步消化食物",
    dailyFact: "分泌约 1.5–2 升胃液",
    medical: "胃黏膜每 3–4 天更新一次，以免被自身胃酸侵蚀。",
    bloodSupply: "胃左、胃右与胃网膜动脉",
    funFact: "胃酸的 pH 可低至 1.5–2.0——足以溶解锌，却伤不到胃壁本身。",
    illustrated: true,
    hotspots: [
      { id: "cardia", label: "贲门", detail: "连接食管，防止反流", position: [0.5, 1.1, 0.6], color: "#6393d8" },
      { id: "fundus", label: "胃底", detail: "食物与气体的暂存区", position: [1.25, 0.85, 0.5], color: "#f2a33b" },
      { id: "body", label: "胃体", detail: "研磨与消化的主区域", position: [0, 0, 1.5], color: "#ee7c6a" },
      { id: "pylorus", label: "幽门", detail: "控制食糜进入十二指肠", position: [-1.25, -1.0, 0.7], color: "#d89bc4" },
    ],
  },
  {
    id: "esophagus",
    name: "食管",
    scientificName: "Oesophagus",
    system: "消化系统",
    model: "/models/esophagus.glb",
    icon: "∥",
    accent: "#d9a98c",
    description: "一条长约 25 厘米的肌性管道，通过蠕动波把食团从咽部一路推送进胃。",
    poetic: "食物的滑道",
    size: "长约 25 厘米，直径约 2 厘米",
    weight: "薄壁肌性管道",
    location: "咽部与胃之间，穿行胸腔",
    function: "蠕动输送食团",
    dailyFact: "配合每天上千次吞咽",
    medical: "下食管括约肌防止胃酸反流入胸腔。",
    bloodSupply: "甲状腺下动脉与胃左动脉分支",
    funFact: "食团靠蠕动推进，不靠重力——倒立时也能正常喝水。",
    illustrated: true,
    hotspots: [
      { id: "cervical", label: "颈段", detail: "起自咽部", position: [0, 1.5, 0.25], color: "#6393d8" },
      { id: "thoracic", label: "胸段", detail: "穿行于心脏后方", position: [0, 0, 0.3], color: "#f2a33b" },
      { id: "junction", label: "食管胃连接部", detail: "穿过膈肌进入胃", position: [0.15, -1.8, 0.3], color: "#ee7c6a" },
    ],
  },
  {
    id: "spleen",
    name: "脾",
    scientificName: "Splen",
    system: "淋巴系统",
    model: "/models/spleen.glb",
    icon: "◑",
    accent: "#b06a78",
    description: "人体最大的淋巴器官，过滤血液、清除衰老血细胞，并储存免疫细胞与血小板。",
    poetic: "血液的净化站",
    size: "约一个拳头大小，长约 11 厘米",
    weight: "约 150 克",
    location: "左上腹，第 9–11 肋深面",
    function: "过滤血液并参与免疫",
    dailyFact: "储存全身约 1/3 的血小板",
    medical: "位置贴近肋骨，外伤时是腹腔内最易破裂的器官。",
    bloodSupply: "脾动脉与脾静脉",
    funFact: "被切除后人依然可以存活——肝脏和骨髓会接管它的大部分工作。",
    illustrated: true,
    hotspotSize: 26,
    hotspots: [
      { id: "hilum", label: "脾门", detail: "血管与淋巴管出入处", position: [0.33, -0.14, 0.9], color: "#ee7c6a" },
      { id: "diaphragmatic-surface", label: "膈面", detail: "光滑凸起，贴近左侧膈肌", position: [0, 0.15, -1.25], color: "#f2a33b" },
      { id: "gastric-surface", label: "胃面", detail: "脏面上与胃相邻的区域", position: [-0.08, 0.72, 0.65], color: "#6393d8" },
      { id: "renal-surface", label: "肾面", detail: "靠近左肾上部的脾脏表面", position: [-0.13, -0.82, -0.55], color: "#d89bc4" },
      { id: "colic-surface", label: "结肠面", detail: "与结肠脾曲相邻的下部表面", position: [1.3, -1.06, 1], color: "#7fa88a" },
    ],
  },
  {
    id: "gallbladder",
    name: "胆囊",
    scientificName: "Vesica biliaris",
    system: "消化系统",
    model: "/models/gallbladder.glb",
    icon: "❍",
    accent: "#7fa88a",
    description: "藏在肝脏下方的梨形囊袋，浓缩并储存胆汁，进食脂肪时将其排入十二指肠。",
    poetic: "胆汁的仓库",
    size: "长约 7–10 厘米",
    weight: "可储存约 50 毫升胆汁",
    location: "右上腹，肝脏下面",
    function: "浓缩、储存与排放胆汁",
    dailyFact: "肝脏每天分泌约 800–1000 毫升胆汁",
    medical: "胆固醇过饱和时容易在囊内形成结石。",
    bloodSupply: "胆囊动脉（多源自肝右动脉）",
    funFact: "它能把肝脏送来的胆汁浓缩到原来的十分之一。",
    illustrated: true,
    hotspots: [
      { id: "gb-fundus", label: "胆囊底", detail: "圆钝突出的下端", position: [-0.15, -1.8, -0.3], color: "#f2a33b" },
      { id: "gb-body", label: "胆囊体", detail: "储存胆汁的主体", position: [0.2, 0, 1.0], color: "#ee7c6a" },
      { id: "gb-neck", label: "胆囊颈", detail: "连接胆囊管", position: [0.4, 1.7, 0.3], color: "#6393d8" },
    ],
  },
  {
    id: "bladder",
    name: "膀胱",
    scientificName: "Vesica urinaria",
    system: "泌尿系统",
    model: "/models/bladder.glb",
    icon: "▽",
    accent: "#c9a25e",
    description: "富有弹性的肌性储尿囊，充盈时升入腹腔，排空后缩回盆腔。",
    poetic: "身体的蓄水池",
    size: "容量约 400–500 毫升",
    weight: "空虚时约 50 克",
    location: "盆腔前部，耻骨联合后方",
    function: "储存并排出尿液",
    dailyFact: "每天排尿约 4–8 次",
    medical: "尿液达到约 150–250 毫升时便会产生尿意。",
    bloodSupply: "膀胱上、下动脉",
    funFact: "它的内壁布满皱襞，充盈时会被撑平——容积可扩大近十倍。",
    illustrated: true,
    hotspots: [
      { id: "dome", label: "膀胱穹窿", detail: "充盈时升高的顶部", position: [0, 0.6, 1.5], color: "#f2a33b" },
      { id: "trigone", label: "膀胱三角", detail: "两输尿管口与尿道内口之间", position: [0.15, -0.1, -1.44], color: "#6393d8" },
      { id: "ureteric", label: "输尿管口", detail: "输尿管进入膀胱处", position: [1.38, 0.56, -1.52], color: "#d89bc4" },
      { id: "neck", label: "膀胱颈", detail: "连接尿道", position: [0.2, -1.0, -0.5], color: "#ee7c6a" },
    ],
  },
  {
    id: "trachea",
    name: "气管",
    scientificName: "Trachea",
    system: "呼吸系统",
    model: "/models/trachea.glb",
    icon: "⋮",
    accent: "#cf9d90",
    description: "由 C 形软骨环支撑的通气管道，把空气导入支气管，同时加温、湿润并清扫它。",
    poetic: "空气的长廊",
    size: "长约 10–12 厘米",
    weight: "由 16–20 个软骨环支撑",
    location: "颈部正中至胸腔，约第 4–5 胸椎处分叉",
    function: "通气并清洁吸入的空气",
    dailyFact: "内壁纤毛不停向上清扫黏液",
    medical: "异物误吸多落入右侧主支气管——它更粗、更直。",
    bloodSupply: "甲状腺下动脉与支气管动脉",
    funFact: "C 形软骨环的缺口朝后，给身后的食管留出吞咽扩张的空间。",
    illustrated: true,
    hotspots: [
      { id: "rings", label: "气管软骨环", detail: "C 形透明软骨保持气道持续开放", position: [-0.11, 0.99, 0.91], color: "#f2a33b" },
      { id: "membrane", label: "气管膜性后壁", detail: "软骨环缺口处的平滑肌壁，为身后的食管留出吞咽空间", position: [0.14, -0.46, -0.67], color: "#6393d8" },
      { id: "carina", label: "气管杈", detail: "分为左、右主支气管", position: [0.11, -1.9, -1.06], color: "#ee7c6a" },
    ],
  },
  {
    id: "larynx",
    name: "喉",
    scientificName: "Larynx",
    system: "呼吸系统",
    model: "/models/larynx.glb",
    icon: "◫",
    accent: "#b98c9a",
    description: "位于咽与气管之间的软骨性通道，既保护下呼吸道，也是声音产生的关键结构。",
    poetic: "呼吸与声音的门廊",
    size: "成人高度约 4–5 厘米",
    weight: "由多块软骨、韧带和肌肉共同构成",
    location: "颈前部，第 3–6 颈椎水平",
    function: "维持气道、保护吞咽并参与发声",
    dailyFact: "说话时喉内结构会进行快速而精细的协调运动",
    medical: "喉部水肿、异物或肿瘤可能迅速影响通气与发声。",
    bloodSupply: "喉上动脉与喉下动脉",
    funFact: "吞咽时整个喉会向上移动，帮助会厌保护气道入口。",
    illustrated: true,
    hotspotSize: 23,
    hotspots: [
      { id: "thyroid-cartilage", label: "甲状软骨", detail: "喉部最大的软骨，前方形成喉结轮廓", position: [0, 0.3, 0.16], color: "#ee7c6a" },
      { id: "cricoid-cartilage", label: "环状软骨", detail: "唯一完整环绕气道的喉软骨", position: [-0.04, -1.07, -0.48], color: "#6393d8" },
      { id: "epiglottis", label: "会厌软骨", detail: "吞咽时帮助覆盖喉入口", position: [-0.06, 0.9, 0.25], color: "#7fa88a" },
      { id: "left-arytenoid", label: "左杓状软骨", detail: "参与调节声带位置与张力", position: [0.45, -0.05, -0.37], color: "#f2a33b" },
      { id: "right-arytenoid", label: "右杓状软骨", detail: "与对侧共同控制声门开合", position: [-0.4, -0.05, -0.33], color: "#d89bc4" },
      { id: "corniculate", label: "小角软骨", detail: "位于杓状软骨顶部的小型成对软骨", position: [0.29, 0.63, -0.21], color: "#c9956a" },
    ],
  },
  {
    id: "main-bronchus",
    name: "主支气管",
    scientificName: "Bronchi principales",
    system: "呼吸系统",
    model: "/models/main-bronchus.glb",
    icon: "⌁",
    accent: "#c49589",
    description: "气管分叉后进入左右肺的两条主要气道，继续分成叶支气管和更细的支气管树。",
    poetic: "空气通往双肺的岔路",
    size: "右侧较短而直，左侧较长而斜",
    weight: "由黏膜、平滑肌与软骨支撑",
    location: "气管杈至左右肺门之间",
    function: "把空气分别输送到左右肺",
    dailyFact: "吸入空气在这里开始进入两侧不同的支气管树",
    medical: "右主支气管更粗、更短、更直，因此吸入异物更容易进入右侧。",
    bloodSupply: "支气管动脉",
    funFact: "左右主支气管并不对称，这种差异会直接影响异物误吸的位置。",
    illustrated: true,
    hotspotSize: 24,
    hotspots: [
      { id: "right-main", label: "右主支气管", detail: "较短、较粗并以较陡角度进入右肺", position: [-1.17, -0.05, 0.04], color: "#ee7c6a" },
      { id: "right-cartilage", label: "右侧支气管软骨", detail: "维持右主支气管通畅的软骨支架", position: [-0.92, 0.55, 0.35], color: "#f2a33b" },
      { id: "left-main", label: "左主支气管", detail: "较长、较细并绕过心脏大血管进入左肺", position: [0.81, 0.2, 0], color: "#6393d8" },
      { id: "left-cartilage", label: "左侧支气管软骨", detail: "支撑左主支气管管壁", position: [0.9, -0.35, 0.3], color: "#d89bc4" },
    ],
  },
  {
    id: "appendix",
    name: "阑尾",
    scientificName: "Appendix vermiformis",
    system: "消化系统",
    model: "/models/appendix.glb",
    icon: "∿",
    accent: "#dda086",
    description: "盲肠末端伸出的一条细管，是肠道有益菌群躲避风雨的“安全屋”。",
    poetic: "肠道菌的避难所",
    size: "长约 6–9 厘米",
    weight: "细如蚯蚓，仅数克",
    location: "右下腹，盲肠末端",
    function: "储存有益的肠道菌群",
    dailyFact: "管腔极细，容易被粪石堵塞",
    medical: "阑尾炎发作时需及时处理，穿孔可致腹膜炎。",
    bloodSupply: "阑尾动脉（回结肠动脉分支）",
    funFact: "它曾被认为是退化无用的器官，如今被视为肠道菌群的后备仓库。",
    illustrated: true,
    hotspots: [
      { id: "base", label: "阑尾根部", detail: "连接盲肠", position: [1.5, -0.2, 0.4], color: "#f2a33b" },
      { id: "shaft", label: "阑尾体", detail: "细长的盲管", position: [0, 0, 0.9], color: "#ee7c6a" },
      { id: "tip", label: "阑尾尖", detail: "游离的末端", position: [-1.6, 0.4, 0.6], color: "#6393d8" },
    ],
  },
  {
    id: "tongue",
    name: "舌",
    scientificName: "Lingua",
    system: "消化系统",
    model: "/models/tongue.glb",
    icon: "∽",
    accent: "#d9796a",
    description: "由八块肌肉交织而成的灵活器官，搅拌食物、感受味道并协助发音。",
    poetic: "味道的舞台",
    size: "长约 8–10 厘米",
    weight: "由 8 块肌肉交织而成",
    location: "口腔之内",
    function: "搅拌食物、味觉与发音",
    dailyFact: "分布着约 2,000–4,000 个味蕾",
    medical: "味蕾每 10–14 天就会更新一轮。",
    bloodSupply: "舌动脉（颈外动脉分支）",
    funFact: "“味觉分区图”是讹传——舌头的各个区域都能尝出五种基本味道。",
    illustrated: true,
    hotspots: [
      { id: "tip", label: "舌尖", detail: "最灵活的部分", position: [0.2, 0.5, 1.7], color: "#ee7c6a" },
      { id: "body", label: "舌体", detail: "味蕾密布的区域", position: [0, 0.3, 0.8], color: "#f2a33b" },
      { id: "root", label: "舌根", detail: "连接会厌与咽部", position: [0.3, -0.5, -1.3], color: "#6393d8" },
    ],
  },
  {
    id: "ear",
    name: "耳",
    scientificName: "Auris externa",
    system: "感觉系统",
    model: "/models/ear.glb",
    icon: "◖",
    accent: "#d4a184",
    description: "耳廓收集声波并导入耳道，经鼓膜与听小骨接力，最终转化为神经信号。",
    poetic: "声音的收集器",
    size: "耳廓高约 6 厘米",
    weight: "仅数克重",
    location: "头部两侧",
    function: "收集并传导声波",
    dailyFact: "双耳靠时间差分辨声源方向",
    medical: "鼓膜只有约 0.1 毫米厚，却能高效传递振动。",
    bloodSupply: "耳后动脉与颞浅动脉",
    funFact: "人的耳朵一辈子都在缓慢长大——软骨会持续生长。",
    illustrated: true,
    hotspots: [
      { id: "helix", label: "耳轮", detail: "耳廓外缘的卷曲", position: [0.3, 1.4, 0.5], color: "#f2a33b" },
      { id: "concha", label: "耳甲", detail: "声波汇集的凹陷", position: [-0.2, 0, 0.9], color: "#ee7c6a" },
      { id: "lobule", label: "耳垂", detail: "没有软骨的柔软末端", position: [-0.5, -1.5, 0.9], color: "#6393d8" },
    ],
  },
  {
    id: "adrenal",
    name: "肾上腺",
    scientificName: "Glandula suprarenalis",
    system: "内分泌系统",
    model: "/models/adrenal.glb",
    icon: "▲",
    accent: "#bf9b52",
    description: "骑在两侧肾上极的小腺体，外层分泌皮质激素，核心分泌肾上腺素。",
    poetic: "应激的开关",
    size: "骑在肾上极的小三角帽",
    weight: "每个仅约 4–5 克",
    location: "两侧肾脏上方",
    function: "分泌肾上腺素与皮质激素",
    dailyFact: "应激时几秒内心率和血压上升",
    medical: "皮质分泌皮质醇，髓质分泌肾上腺素，各司其职。",
    bloodSupply: "肾上腺上、中、下三组动脉",
    funFact: "名字相当直白——“肾上腺”就是“长在肾上面的腺体”。",
    illustrated: true,
    hotspots: [
      { id: "left", label: "左肾上腺", detail: "半月形，贴左肾上极", position: [-1.36, -0.23, 0.5], color: "#f2a33b" },
      { id: "right", label: "右肾上腺", detail: "三角形，贴右肾上极", position: [1.16, 0.32, 0.4], color: "#6393d8" },
      { id: "medulla", label: "肾上腺髓质", detail: "分泌肾上腺素", position: [-1.3, 0.3, 0.3], color: "#ee7c6a" },
    ],
  },
  {
    id: "diaphragm",
    name: "膈肌",
    scientificName: "Diaphragma",
    system: "呼吸系统",
    model: "/models/diaphragm.glb",
    icon: "◠",
    accent: "#bd7f6e",
    description: "隔开胸腔与腹腔的穹窿状肌肉，它的收缩舒张驱动每一次呼吸。",
    poetic: "呼吸的引擎",
    size: "穹窿状，厚仅数毫米",
    weight: "最重要的呼吸肌",
    location: "胸腔与腹腔之间",
    function: "收缩产生吸气",
    dailyFact: "每天随呼吸运动约 2 万次",
    medical: "打嗝就是膈肌不自主的痉挛。",
    bloodSupply: "膈上、膈下动脉",
    funFact: "咳嗽、呕吐和排便时的腹压，也都有它参与。",
    illustrated: true,
    hotspots: [
      { id: "central-tendon", label: "中心腱", detail: "穹窿顶部的腱膜", position: [0, 1.2, 0.9], color: "#f2a33b" },
      { id: "caval", label: "腔静脉孔", detail: "下腔静脉穿过处", position: [0.7, 0.5, 0.8], color: "#6393d8" },
      { id: "esophageal", label: "食管裂孔", detail: "食管穿过处", position: [-0.3, 0.1, 0.7], color: "#ee7c6a" },
      { id: "aortic", label: "主动脉裂孔", detail: "主动脉穿过处", position: [-0.2, -0.9, -0.6], color: "#d89bc4" },
    ],
  },
  {
    id: "thymus",
    name: "胸腺",
    scientificName: "Thymus",
    system: "淋巴系统",
    model: "/models/thymus.glb",
    icon: "❋",
    accent: "#b98aa6",
    description: "位于胸骨后方的免疫“学校”，T 淋巴细胞在这里学习识别敌我。",
    poetic: "免疫的学校",
    size: "青春期时最大",
    weight: "青春期约 30–40 克",
    location: "胸骨后方，心脏上方",
    function: "培育成熟的 T 淋巴细胞",
    dailyFact: "青春期后逐渐脂肪化",
    medical: "重症肌无力常与胸腺异常相关。",
    bloodSupply: "胸廓内动脉分支",
    funFact: "它会随年龄“退休”——成年后大部分被脂肪组织替代。",
    illustrated: true,
    hotspots: [
      { id: "left-lobe", label: "左叶", detail: "胸腺的两个叶之一", position: [-0.5, 0.2, 0.5], color: "#f2a33b" },
      { id: "right-lobe", label: "右叶", detail: "两叶在中线会合", position: [0.4, 0.1, 0.6], color: "#6393d8" },
    ],
  },
  {
    id: "spinal-cord",
    name: "脊髓",
    scientificName: "Medulla spinalis",
    system: "神经系统",
    model: "/models/spinal-cord.glb",
    icon: "┃",
    accent: "#a08fc4",
    description: "大脑与身体之间的信息高速公路，藏于椎管之内，还能独立完成反射。",
    poetic: "信息的高速公路",
    size: "长约 42–45 厘米",
    weight: "约 30–35 克",
    location: "椎管内，枕骨大孔至第 1–2 腰椎",
    function: "传递神经信号并完成反射",
    dailyFact: "每秒传递数以百万计的信号",
    medical: "损伤平面以下的感觉与运动功能会受损。",
    bloodSupply: "脊髓前、后动脉",
    funFact: "膝跳反射不经过大脑——脊髓自己就能完成整个反射弧。",
    illustrated: true,
    hotspots: [
      { id: "cervical", label: "颈段", detail: "支配上肢的膨大区", position: [0, 1.5, 0.4], color: "#6393d8" },
      { id: "thoracic", label: "胸段", detail: "最长的一段", position: [-0.05, 0.1, 0.2], color: "#f2a33b" },
      { id: "lumbosacral", label: "腰骶段", detail: "末端延续为马尾", position: [0.05, -1.6, 0.2], color: "#ee7c6a" },
    ],
  },
  {
    id: "uterus",
    name: "子宫",
    scientificName: "Uterus",
    system: "生殖系统",
    model: "/models/uterus.glb",
    icon: "◡",
    accent: "#cf7f8f",
    description: "梨形的肌性器官，内膜每月周期性更新，受孕后孕育胎儿直至分娩。",
    poetic: "生命的摇篮",
    size: "未孕时长约 7–8 厘米",
    weight: "约 50–70 克",
    location: "盆腔中央，膀胱与直肠之间",
    function: "孕育胎儿并产生月经",
    dailyFact: "孕期可增大数十倍",
    medical: "子宫内膜每月周期性增生与脱落。",
    bloodSupply: "子宫动脉（髂内动脉分支）",
    funFact: "怀孕时，它能从梨子大小扩张到西瓜大小。",
    illustrated: true,
    hotspotSize: 26,
    hotspots: [
      { id: "fundus", label: "子宫底", detail: "输卵管入口以上的顶部", position: [0.13, 0.79, 1.2], color: "#f2a33b" },
      { id: "body", label: "子宫体", detail: "胎儿发育的场所", position: [0.12, 0.37, 0.6], color: "#ee7c6a" },
      { id: "cornua", label: "子宫角", detail: "子宫体上外侧与输卵管相接的区域", position: [1.35, 0.78, 1.02], color: "#7fa88a" },
      { id: "lower-segment", label: "子宫下段", detail: "子宫体与宫颈之间的过渡区域", position: [0.1, -0.12, -0.47], color: "#c58696" },
      { id: "cervix", label: "子宫颈", detail: "通向阴道的门户", position: [0.15, -0.54, -1.22], color: "#6393d8" },
      { id: "internal-os", label: "宫颈内口", detail: "子宫腔进入宫颈管的开口", position: [0.18, -0.3, -0.69], color: "#b887a4" },
      { id: "external-os", label: "宫颈外口", detail: "宫颈管通向阴道的开口", position: [0.19, -0.85, -1.58], color: "#c9956a" },
      { id: "tube", label: "输卵管口", detail: "输卵管进入子宫处", position: [-0.19, 0.79, 1.03], color: "#d89bc4" },
    ],
  },
  {
    id: "ovary",
    name: "卵巢",
    scientificName: "Ovarium",
    system: "生殖系统",
    model: "/models/ovary.glb",
    icon: "◐",
    accent: "#c9879b",
    description: "杏仁大小的腺体，储存卵泡、周期性排卵，并分泌雌激素与孕激素。",
    poetic: "卵子的宝库",
    size: "长约 3–4 厘米，如杏仁",
    weight: "约 5–6 克",
    location: "盆腔内，子宫两侧",
    function: "排卵并分泌性激素",
    dailyFact: "卵泡储备在出生前就已备好",
    medical: "多囊卵巢是常见的内分泌紊乱。",
    bloodSupply: "卵巢动脉（腹主动脉分支）",
    funFact: "出生时卵巢里有一两百万个卵泡，到青春期只剩约 30 万个。",
    illustrated: false,
    hotspots: [
      { id: "cortex", label: "卵巢皮质", detail: "卵泡所在的区域", position: [0.3, 0.4, 0.9], color: "#ee7c6a" },
      { id: "hilum", label: "卵巢门", detail: "血管与神经出入处", position: [-0.4, -0.4, 0.4], color: "#6393d8" },
    ],
  },
  {
    id: "prostate",
    name: "前列腺",
    scientificName: "Prostata",
    system: "生殖系统",
    model: "/models/prostate.glb",
    icon: "❖",
    accent: "#9b86b8",
    description: "倒扣在膀胱出口的栗子形腺体，分泌的液体是精液的主要成分。",
    poetic: "膀胱的守门人",
    size: "栗子大小，约 3–4 厘米",
    weight: "约 20 克",
    location: "膀胱下方，包绕尿道起始部",
    function: "分泌前列腺液",
    dailyFact: "随年龄增长容易增生变大",
    medical: "增生后压迫尿道，导致排尿困难。",
    bloodSupply: "膀胱下动脉分支",
    funFact: "尿道从它正中穿过——所以它一变大，排尿就先受影响。",
    illustrated: false,
    hotspotSize: 23,
    hotspots: [
      { id: "base", label: "前列腺底", detail: "紧贴膀胱颈", position: [-0.2, -0.6, 0.8], color: "#f2a33b" },
      { id: "apex", label: "前列腺尖", detail: "朝向尿生殖膈", position: [-0.16, -1.41, 0.5], color: "#6393d8" },
      { id: "peripheral-zone", label: "外周带", detail: "占腺体大部，前列腺癌最常起源的区域", position: [0.17, -0.8, 0.22], color: "#7fa88a" },
      { id: "transition-zone", label: "移行带", detail: "围绕近端尿道，良性前列腺增生常发生于此", position: [-0.39, -0.72, 0.4], color: "#c58696" },
      { id: "central-zone", label: "中央带", detail: "环绕射精管的腺体区域", position: [-0.44, -0.43, 0.08], color: "#b887a4" },
      { id: "ejaculatory-duct", label: "射精管", detail: "穿过前列腺并开口于前列腺部尿道", position: [-0.16, -0.73, 0.16], color: "#c9956a" },
      { id: "seminal", label: "精囊", detail: "成对的分泌腺体", position: [-0.28, 0.45, -0.2], color: "#ee7c6a" },
      { id: "vas", label: "输精管", detail: "输送精子的管道", position: [-1.3, 1.11, -0.1], color: "#d89bc4" },
    ],
  },
  {
    id: "ureter",
    name: "输尿管",
    scientificName: "Ureter",
    system: "泌尿系统",
    model: "/models/ureter.glb",
    icon: "⋀",
    accent: "#c9956a",
    description: "连接肾盂与膀胱的细长肌性管道，靠一波波蠕动把尿液挤进膀胱。",
    poetic: "尿液的传送带",
    size: "长约 25–30 厘米，直径仅 3–4 毫米",
    weight: "细长的肌性管道",
    location: "肾盂与膀胱之间，贴后腹膜下行",
    function: "蠕动输送尿液",
    dailyFact: "每分钟蠕动数次推送尿液",
    medical: "结石常卡在它的三处生理性狭窄。",
    bloodSupply: "肾动脉与髂动脉的分支",
    funFact: "尿液不是靠重力下流，而是被管壁一波波挤进膀胱的。",
    illustrated: true,
    viewScale: 1.2,
    hotspotSize: 23,
    hotspots: [
      { id: "left-minor-calyces", label: "左侧小肾盏", detail: "从肾乳头收集尿液的杯状末端", position: [0.82, 1.82, -0.4], color: "#7fa88a" },
      { id: "left-major-calyces", label: "左侧大肾盏", detail: "汇合多个小肾盏并通向肾盂", position: [0.84, 1.55, -0.17], color: "#c9956a" },
      { id: "left-pelvis", label: "左侧肾盂", detail: "漏斗状收集尿液并连接输尿管", position: [0.74, 1.48, -0.03], color: "#f2a33b" },
      { id: "right-pelvis", label: "右侧肾盂", detail: "右肾集合系统通向输尿管的位置", position: [-0.74, 1.14, 0.24], color: "#d89bc4" },
      { id: "left-ureter", label: "左侧输尿管", detail: "贴后腹膜向盆腔蠕动下行", position: [0.41, -0.25, 0.1], color: "#ee7c6a" },
      { id: "right-ureter", label: "右侧输尿管", detail: "将右侧肾盂中的尿液送向膀胱", position: [-0.47, -0.36, 0.15], color: "#6393d8" },
    ],
  },
  {
    id: "fallopian-tubes",
    name: "输卵管",
    scientificName: "Tubae uterinae",
    system: "生殖系统",
    model: "/models/fallopian-tubes.glb",
    icon: "∿",
    accent: "#cf8294",
    description: "连接子宫与卵巢附近腹膜腔的成对管道，以纤毛和肌肉收缩运输卵细胞，受精通常也发生在这里。",
    poetic: "生命相遇的通道",
    size: "每侧长约 10–12 厘米",
    weight: "成对的细长肌性管道",
    location: "子宫两侧，延伸至卵巢附近",
    function: "运输卵细胞与早期胚胎",
    dailyFact: "管壁纤毛持续朝子宫方向摆动",
    medical: "输卵管堵塞可影响受孕，胚胎在管内着床则形成异位妊娠。",
    bloodSupply: "子宫动脉与卵巢动脉分支",
    funFact: "输卵管末端并不与卵巢密封连接，而是由伞状的输卵管伞捕捉排出的卵细胞。",
    illustrated: true,
    hotspotSize: 25,
    hotspots: [
      { id: "left-ampulla", label: "左侧壶腹部", detail: "最宽、最常发生受精的部分", position: [1.46, 0.05, 0.14], color: "#ee7c6a" },
      { id: "left-isthmus", label: "左侧峡部", detail: "靠近子宫的狭窄肌性段", position: [0.88, -0.6, 0.18], color: "#7fa88a" },
      { id: "left-infundibulum", label: "左侧漏斗部", detail: "以输卵管伞朝向卵巢", position: [1.6, 0.52, -0.07], color: "#f2a33b" },
      { id: "left-fimbriae", label: "左侧输卵管伞", detail: "指状突起帮助捕捉排出的卵细胞", position: [1.55, 0.34, -0.07], color: "#c9956a" },
      { id: "right-ampulla", label: "右侧壶腹部", detail: "纤毛与蠕动共同运输卵细胞", position: [-1.5, 0.03, 0.04], color: "#d89bc4" },
      { id: "right-isthmus", label: "右侧峡部", detail: "靠近子宫的狭窄肌性段", position: [-0.98, -0.63, 0.16], color: "#6393d8" },
      { id: "right-infundibulum", label: "右侧漏斗部", detail: "输卵管外侧端的漏斗状部分", position: [-1.75, 0.5, -0.27], color: "#b887a4" },
      { id: "right-fimbriae", label: "右侧输卵管伞", detail: "末端指状突起与卵巢表面相邻", position: [-1.73, 0.32, -0.27], color: "#ee7c6a" },
    ],
  },
  {
    id: "mammary-glands",
    name: "乳腺（女性参考）",
    scientificName: "Glandulae mammariae",
    system: "生殖系统",
    model: "/models/mammary-glands.glb",
    icon: "◒",
    accent: "#c98596",
    description: "位于胸前皮下的成对腺体，由乳腺叶、输乳管、脂肪和支持韧带构成，在哺乳期产生并输送乳汁。",
    poetic: "哺育生命的腺体",
    size: "大小和形态随年龄、激素及生育状态明显变化",
    weight: "主要由腺体与脂肪组织构成",
    location: "胸大肌前方的浅筋膜内",
    function: "产生并经乳管输送乳汁",
    dailyFact: "腺体组织会随月经周期、妊娠与哺乳发生变化",
    medical: "乳腺结节需要结合影像与临床判断，腋尾也是检查的重要区域。",
    bloodSupply: "胸廓内动脉、胸外侧动脉及肋间动脉分支",
    funFact: "乳腺不是一个空腔，而是由许多腺叶和逐级汇合的乳管组成。",
    illustrated: true,
    hotspotSize: 20,
    hotspots: [
      { id: "left-nipple", label: "左乳头", detail: "主要输乳管开口集中的表面结构", position: [1.43, -0.6, 0.71], color: "#ee7c6a" },
      { id: "left-lobes", label: "左侧乳腺叶", detail: "由产生乳汁的腺泡及小叶组成", position: [1.31, -0.31, 0.22], color: "#f2a33b" },
      { id: "left-ducts", label: "左侧输乳管", detail: "把各腺叶分泌物汇集到乳头", position: [1.36, -0.33, 0.36], color: "#6393d8" },
      { id: "left-ligaments", label: "左侧乳房悬韧带", detail: "结缔组织束，为乳房提供内部支撑", position: [1.32, -0.58, 0.33], color: "#7fa88a" },
      { id: "right-nipple", label: "右乳头", detail: "右侧输乳管在体表的集中开口区域", position: [-1.44, -0.59, 0.7], color: "#d89bc4" },
      { id: "right-lobes", label: "右侧乳腺叶", detail: "呈放射状排列的腺体组织", position: [-1.32, -0.29, 0.21], color: "#c58696" },
      { id: "right-ducts", label: "右侧输乳管", detail: "连接腺叶与乳头的分支管道", position: [-1.37, -0.31, 0.36], color: "#c9956a" },
      { id: "right-ligaments", label: "右侧乳房悬韧带", detail: "从皮肤延伸至深筋膜的支持结构", position: [-1.33, -0.56, 0.33], color: "#b887a4" },
    ],
  },
  {
    id: "palatine-tonsils",
    name: "腭扁桃体",
    scientificName: "Tonsillae palatinae",
    system: "淋巴系统",
    model: "/models/palatine-tonsils.glb",
    icon: "◖",
    accent: "#b98592",
    description: "位于口咽两侧扁桃体窝内的成对淋巴组织，是咽部免疫环的重要组成部分。",
    poetic: "咽喉入口的免疫哨站",
    size: "每侧通常高约 2 厘米，个体差异明显",
    weight: "由淋巴组织构成",
    location: "腭舌弓与腭咽弓之间",
    function: "接触吸入或吞入的抗原并参与免疫应答",
    dailyFact: "表面隐窝增加了淋巴组织与外界物质接触的面积",
    medical: "反复感染或显著肥大可能造成咽痛、吞咽困难或睡眠呼吸问题。",
    bloodSupply: "面动脉扁桃体支及邻近动脉分支",
    funFact: "腭扁桃体只是咽淋巴环的一部分，鼻咽和舌根附近还有其他扁桃体组织。",
    illustrated: true,
    hotspots: [
      { id: "left-tonsil", label: "左腭扁桃体", detail: "位于左侧扁桃体窝的淋巴组织", position: [1.23, 0, 0], color: "#ee7c6a" },
      { id: "right-tonsil", label: "右腭扁桃体", detail: "位于右侧扁桃体窝的淋巴组织", position: [-1.21, -0.02, -0.01], color: "#6393d8" },
    ],
  },
  {
    id: "lymph-node",
    name: "淋巴结",
    scientificName: "Nodus lymphoideus",
    system: "淋巴系统",
    model: "/models/lymph-node.glb",
    icon: "⬡",
    accent: "#b887a4",
    description: "分布在淋巴管沿途的豆形免疫器官，过滤淋巴液并为淋巴细胞识别抗原、启动免疫反应提供场所。",
    poetic: "免疫的检查站",
    size: "通常数毫米至约 2 厘米",
    weight: "单枚通常不足 1 克",
    location: "颈部、腋窝、胸腹腔与腹股沟等处成群分布",
    function: "过滤淋巴液并组织免疫应答",
    dailyFact: "全身有数百枚淋巴结协同工作",
    medical: "感染、炎症和肿瘤都可能导致淋巴结增大，其位置与形态需要结合临床判断。",
    bloodSupply: "淋巴结门处的小动脉分支",
    funFact: "淋巴结肿大往往说明免疫细胞正在活跃增殖，并不等同于肿瘤。",
    illustrated: true,
    hotspotSize: 22,
    hotspots: [
      { id: "afferent", label: "输入淋巴管", detail: "从凸面把组织淋巴液送入淋巴结", position: [-0.47, -0.71, -0.37], color: "#7fa88a" },
      { id: "capsule", label: "被膜", detail: "包裹淋巴结的结缔组织外壳", position: [1.65, 0.1, 0.15], color: "#ee7c6a" },
      { id: "follicles", label: "淋巴滤泡", detail: "B 淋巴细胞聚集与增殖的区域", position: [-1.1, 0.45, 0.7], color: "#d89bc4" },
      { id: "paracortex", label: "副皮质区", detail: "以 T 淋巴细胞为主的免疫应答区域", position: [-0.3, 0.15, 0.4], color: "#c58696" },
      { id: "medulla", label: "髓质", detail: "含髓索与髓窦的内层区域", position: [0.3, -0.2, 0.75], color: "#f2a33b" },
      { id: "blood-vasculature", label: "淋巴结血管", detail: "为免疫细胞和基质组织提供血液供应", position: [0.7, 0.2, 0.4], color: "#c9956a" },
      { id: "efferent", label: "输出淋巴管", detail: "由淋巴结门将淋巴液带出", position: [0.07, 0.6, 0.31], color: "#6393d8" },
    ],
  },
  {
    id: "blood-vessels",
    name: "血管",
    scientificName: "Vasa sanguinea",
    system: "心血管系统",
    model: "/models/blood-vessels.glb",
    icon: "⌇",
    accent: "#b86f78",
    description: "遍布全身的动脉、静脉与毛细血管网络，把血液送到组织并带回代谢产物，是循环系统的运输通道。",
    poetic: "遍布全身的河网",
    size: "大血管直径数厘米，毛细血管仅数微米",
    weight: "连续分支的全身网络",
    location: "从心脏延伸到几乎所有活组织",
    function: "运输血液、调节灌注与体温",
    dailyFact: "静息时心脏每分钟约泵出 5 升血液",
    medical: "动脉粥样硬化、血栓和血管破裂会阻断或泄漏关键组织的血流。",
    bloodSupply: "大血管壁由滋养血管供血，小血管靠腔内扩散",
    funFact: "毛细血管细到红细胞常常需要排成单列才能通过。",
    illustrated: true,
    viewScale: 1.35,
    hotspotSize: 20,
    hotspots: [
      { id: "head-neck-branches", label: "头颈与上肢分支", detail: "颈总动脉、锁骨下动脉等由主动脉弓发出", position: [0.02, 0.8, -0.03], color: "#b887a4" },
      { id: "aortic-arch", label: "主动脉弓", detail: "把左心室输出分配到头颈与全身", position: [0, 0.69, -0.09], color: "#ee7c6a" },
      { id: "pulmonary-circulation", label: "肺循环血管", detail: "肺动脉与肺静脉在心脏和肺之间完成气体交换循环", position: [0.04, 0.52, 0.03], color: "#6393d8" },
      { id: "coronary-circulation", label: "冠状循环", detail: "冠状动脉与心静脉为心肌供血并回流", position: [0.23, 0.3, 0.1], color: "#c58696" },
      { id: "descending-aorta", label: "降主动脉", detail: "沿胸腹部向下输送动脉血", position: [0.04, -0.52, -0.11], color: "#f2a33b" },
      { id: "vena-cava", label: "下腔静脉", detail: "把下半身静脉血送回右心房", position: [-0.14, -0.55, -0.1], color: "#6393d8" },
      { id: "hepatic-portal", label: "肝门静脉系统", detail: "把消化道吸收的物质先送入肝脏处理", position: [-0.13, -0.39, 0], color: "#7fa88a" },
      { id: "renal-vessels", label: "肾血管", detail: "肾动脉和肾静脉连接双肾与腹部大血管", position: [0.17, -0.61, -0.11], color: "#d89bc4" },
      { id: "mesenteric-vessels", label: "肠系膜血管", detail: "为小肠和大肠的大部分区域供血并引流", position: [-0.05, -0.69, 0], color: "#c9956a" },
      { id: "iliac", label: "髂血管", detail: "连接腹部与盆腔、下肢循环", position: [0.05, -1.2, -0.05], color: "#d89bc4" },
    ],
  },
  {
    id: "placenta",
    name: "胎盘",
    scientificName: "Placenta",
    system: "生殖系统",
    model: "/models/placenta.glb",
    icon: "✺",
    accent: "#a96778",
    description: "妊娠期间形成的临时器官，连接母体与胎儿循环，完成气体、营养和代谢物交换并分泌维持妊娠的激素。",
    poetic: "短暂的生命支持站",
    size: "足月时直径约 18–22 厘米",
    weight: "足月时约 500–600 克",
    location: "附着于妊娠子宫内壁",
    function: "母胎交换、内分泌与免疫屏障",
    dailyFact: "妊娠晚期每分钟有大量母体血液流经胎盘间隙",
    medical: "胎盘位置、植入深度或过早分离异常，都可能威胁母体与胎儿安全。",
    bloodSupply: "母体子宫螺旋动脉与胎儿脐动脉、脐静脉",
    funFact: "母体与胎儿的血液通常不会直接混合，交换主要跨越薄薄的胎盘屏障完成。",
    illustrated: true,
    hotspotSize: 23,
    hotspots: [
      { id: "basal-plate", label: "基底板", detail: "朝向母体子宫壁的胎盘表面", position: [-0.1, 0.14, -0.9], color: "#7fa88a" },
      { id: "chorionic-plate", label: "绒毛膜板", detail: "朝向胎儿的光滑表面", position: [-0.11, 0.1, -0.07], color: "#ee7c6a" },
      { id: "placental-vessels", label: "胎盘血管", detail: "由脐带向胎盘表面树状分支", position: [-0.18, 0.15, 0.3], color: "#6393d8" },
      { id: "umbilical-cord", label: "脐带", detail: "连接胎儿与胎盘的血管通道", position: [0.04, -0.69, 0.51], color: "#f2a33b" },
      { id: "umbilical-vessels", label: "脐血管", detail: "通常由两条脐动脉和一条脐静脉组成", position: [0.04, -0.58, 0.62], color: "#c9956a" },
      { id: "amnion", label: "羊膜", detail: "覆盖胎盘胎儿面的薄膜", position: [1.45, 0.5, 0.1], color: "#d89bc4" },
    ],
  },
  {
    id: "urethra",
    name: "尿道（男性参考）",
    scientificName: "Urethra masculina",
    system: "泌尿系统",
    model: "/models/urethra.glb",
    icon: "∣",
    accent: "#c48f71",
    description: "从膀胱颈通向体外的排尿管道；此标本展示男性尿道较长、分段并穿过前列腺与盆底的形态。",
    poetic: "尿液的最后通道",
    size: "男性通常长约 18–20 厘米",
    weight: "细长的黏膜与肌性管道",
    location: "膀胱颈至尿道外口",
    function: "将尿液排出体外",
    dailyFact: "排尿时括约肌协调放松，膀胱逼尿肌收缩",
    medical: "狭窄、感染或损伤会造成排尿困难；导尿操作必须遵循正确解剖路径。",
    bloodSupply: "膀胱下动脉与阴部内动脉分支",
    funFact: "女性尿道通常仅约 4 厘米，和本页男性参考模型在长度与路径上明显不同。",
    illustrated: true,
    hotspots: [
      { id: "prostatic", label: "前列腺部", detail: "穿过前列腺的近端段", position: [-0.1, 1.58, -1.68], color: "#d89bc4" },
      { id: "membranous", label: "膜部", detail: "穿过尿生殖膈，短而相对固定", position: [0.05, 0.65, -0.6], color: "#f2a33b" },
      { id: "spongy", label: "海绵体部", detail: "男性尿道最长的一段", position: [0.05, -0.31, 0.01], color: "#ee7c6a" },
    ],
  },
  {
    id: "skeleton",
    name: "全身骨骼",
    scientificName: "Systema skeletale",
    system: "骨骼系统",
    model: "/models/skeleton.glb",
    icon: "◇",
    accent: "#d2a77e",
    description: "由骨、软骨与关节共同构成的全身支架，保护重要器官、为肌肉提供杠杆，并持续参与矿物质储存和血细胞生成。",
    poetic: "支撑身体的静默框架",
    size: "成人通常有 206 块骨",
    weight: "约占体重的 12%–15%",
    location: "贯穿头、躯干与四肢",
    function: "支撑、保护、运动、造血和矿物质储存",
    dailyFact: "骨组织会持续重塑，以适应负荷并修复微小损伤",
    medical: "骨密度、关节对位和骨折愈合都会影响整体活动能力。",
    bloodSupply: "各骨的滋养动脉、骨膜血管与干骺端血管",
    funFact: "骨不是静止的支架，而是有血管、有细胞并持续更新的活组织。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "skull", label: "颅骨", detail: "包围并保护脑，构成面部与感觉器官的骨性框架", position: [0.29, 1.67, 0], color: "#ee7c6a" },
      { id: "spine", label: "脊柱", detail: "由颈、胸、腰椎及骶尾骨组成，支撑躯干并保护脊髓", position: [0.29, 0.82, -0.14], color: "#6393d8" },
      { id: "rib-cage", label: "胸廓", detail: "肋骨、胸椎与胸骨共同保护心肺", position: [0.29, 0.98, 0.06], color: "#f2a33b" },
      { id: "shoulder-girdle", label: "肩带", detail: "锁骨和肩胛骨把上肢连接到躯干", position: [-0.05, 1.2, -0.06], color: "#7fa88a" },
      { id: "upper-limb", label: "上肢骨", detail: "包括肱骨、桡尺骨以及手部诸骨", position: [-0.25, 0.45, -0.06], color: "#d89bc4" },
      { id: "pelvic-girdle", label: "骨盆", detail: "承接脊柱重量并把躯干负荷传向下肢", position: [0.29, 0.12, -0.08], color: "#c58696" },
      { id: "femur", label: "股骨", detail: "人体最长、最坚固的长骨", position: [0.09, -0.45, -0.07], color: "#c9956a" },
      { id: "lower-leg", label: "小腿骨", detail: "胫骨主要承重，腓骨提供外侧稳定与肌肉附着", position: [0.1, -1.35, -0.1], color: "#b887a4" },
    ],
  },
  {
    id: "shoulder-joint",
    name: "肩关节（右侧参考）",
    scientificName: "Articulatio humeri dextra",
    system: "骨骼系统",
    model: "/models/shoulder-joint.glb",
    icon: "◔",
    accent: "#d39a73",
    description: "以盂肱关节为核心，并由肩胛骨、锁骨、关节唇、关节囊和韧带共同维持活动与稳定的肩部关节复合体。",
    poetic: "灵活与稳定的精细平衡",
    size: "肱骨头明显大于关节盂",
    weight: "由骨、软骨、韧带和关节囊共同构成",
    location: "右侧肩胛骨外侧与肱骨近端之间",
    function: "让上肢完成大范围多轴运动",
    dailyFact: "梳头、穿衣和抬手都需要多个肩部关节协同",
    medical: "肩关节活动度大，稳定性高度依赖关节唇、韧带和周围肌群。",
    bloodSupply: "旋肱前后动脉与肩胛上动脉分支",
    funFact: "浅而小的关节盂换来了很大的活动范围，也让肩关节更依赖软组织稳定。",
    illustrated: true,
    hotspotSize: 20,
    hotspots: [
      { id: "humeral-head", label: "肱骨头", detail: "与肩胛骨关节盂相接的球形关节面", position: [-0.37, 1.48, 0.04], color: "#ee7c6a" },
      { id: "glenoid", label: "关节盂", detail: "肩胛骨外侧较浅的关节窝", position: [-0.22, 1.39, -0.06], color: "#6393d8" },
      { id: "labrum", label: "盂唇", detail: "环绕关节盂边缘并加深关节窝的纤维软骨", position: [-0.23, 1.4, -0.05], color: "#d89bc4" },
      { id: "capsule", label: "盂肱关节囊", detail: "包围关节并容纳滑液的纤维性囊", position: [-0.39, 1.42, 0.06], color: "#f2a33b" },
      { id: "glenohumeral-ligaments", label: "盂肱韧带", detail: "加强关节囊前方并限制过度移位", position: [-0.34, 1.4, 0.19], color: "#7fa88a" },
      { id: "ac-joint", label: "肩锁关节", detail: "肩峰与锁骨外侧端形成的小关节", position: [-0.21, 1.79, -0.05], color: "#c9956a" },
    ],
  },
  {
    id: "elbow-joint",
    name: "肘关节（右侧参考）",
    scientificName: "Articulatio cubiti dextra",
    system: "骨骼系统",
    model: "/models/elbow-joint.glb",
    icon: "⌁",
    accent: "#c99172",
    description: "肱骨、尺骨和桡骨在同一关节囊内组成的复合关节，既完成屈伸，也支持前臂旋前与旋后。",
    poetic: "上肢中段的机械铰链",
    size: "由三个相互关联的关节组成",
    weight: "骨端、软骨、韧带与关节囊共同构成",
    location: "右上臂与前臂交界处",
    function: "完成肘屈伸和前臂旋转",
    dailyFact: "进食、书写和转动门把手都依赖肘与前臂协同",
    medical: "跌倒撑地、重复投掷或长期压迫都可能损伤肘部骨、韧带或神经。",
    bloodSupply: "肱深动脉及尺侧、桡侧返动脉形成的关节网",
    funFact: "看似单纯的肘部弯曲，实际上由三个关节在同一关节囊内配合完成。",
    illustrated: true,
    hotspotSize: 20,
    hotspots: [
      { id: "distal-humerus", label: "肱骨远端", detail: "形成滑车和肱骨小头，与尺桡骨近端相接", position: [-0.06, -0.19, -0.13], color: "#ee7c6a" },
      { id: "ulna", label: "尺骨近端", detail: "鹰嘴与滑车切迹共同形成主要屈伸铰链", position: [0, -0.21, -0.14], color: "#6393d8" },
      { id: "radial-head", label: "桡骨头", detail: "与肱骨小头及尺骨桡切迹相接并参与前臂旋转", position: [-0.15, -0.27, -0.11], color: "#f2a33b" },
      { id: "capsule", label: "肘关节囊", detail: "共同包绕肱尺、肱桡和近侧桡尺关节", position: [-0.02, -0.18, -0.14], color: "#d89bc4" },
      { id: "annular", label: "桡骨环状韧带", detail: "环抱桡骨头并允许其旋转", position: [-0.14, -0.33, -0.1], color: "#7fa88a" },
      { id: "collateral", label: "内外侧副韧带", detail: "抵抗肘关节侧向应力并维持稳定", position: [0.08, -0.28, -0.11], color: "#c9956a" },
    ],
  },
  {
    id: "hip-joint",
    name: "髋关节（右侧参考）",
    scientificName: "Articulatio coxae dextra",
    system: "骨骼系统",
    model: "/models/hip-joint.glb",
    icon: "◕",
    accent: "#c89576",
    description: "股骨头嵌入髋臼形成的负重球窝关节，由深关节窝、盂唇、强韧关节囊和多条韧带共同稳定。",
    poetic: "承托步伐的深球窝",
    size: "股骨头直径通常约 4–5 厘米",
    weight: "骨盆与股骨之间的主要负重关节",
    location: "右侧骨盆外侧与股骨近端之间",
    function: "承重并让下肢完成多轴运动",
    dailyFact: "站立和行走时，髋关节承受的力可超过体重",
    medical: "骨折、发育异常、软骨退变或股骨头血供受损都会显著影响行走。",
    bloodSupply: "旋股内外侧动脉及闭孔动脉分支",
    funFact: "髋臼比肩关节盂更深，因此髋关节牺牲部分活动度换取了更强稳定性。",
    illustrated: true,
    hotspotSize: 20,
    hotspots: [
      { id: "femoral-head", label: "股骨头", detail: "覆盖关节软骨并嵌入髋臼的球形骨端", position: [-0.04, 0.93, 0.06], color: "#ee7c6a" },
      { id: "acetabulum", label: "髋臼", detail: "由髂骨、坐骨和耻骨共同形成的深关节窝", position: [0, 0.94, 0.06], color: "#6393d8" },
      { id: "labrum", label: "髋臼唇", detail: "加深髋臼并帮助维持关节密封", position: [-0.05, 0.93, 0.07], color: "#d89bc4" },
      { id: "capsule", label: "髋关节囊", detail: "强韧的纤维囊包围股骨颈近端", position: [-0.1, 0.77, 0.07], color: "#f2a33b" },
      { id: "iliofemoral", label: "髂股韧带", detail: "人体最强韧的韧带之一，限制站立时髋过度伸展", position: [-0.12, 0.74, 0.14], color: "#7fa88a" },
      { id: "head-ligament", label: "股骨头韧带", detail: "连接股骨头凹与髋臼，并携带小血管分支", position: [0.1, 0.88, 0.1], color: "#c9956a" },
    ],
  },
  {
    id: "ankle-foot",
    name: "踝与足（右侧参考）",
    scientificName: "Articulationes pedis dextri",
    system: "骨骼系统",
    model: "/models/ankle-foot.glb",
    icon: "⌞",
    accent: "#c59a78",
    description: "由胫腓骨远端、距骨、跗骨、跖骨和趾骨及多组韧带构成的负重结构，在稳定与适应地面之间取得平衡。",
    poetic: "承接大地的弹性拱桥",
    size: "单足通常有 26 块骨",
    weight: "由 33 个关节和百余条韧带协同",
    location: "右小腿远端至足趾",
    function: "承重、缓冲冲击并推动步态",
    dailyFact: "足弓在每一步中都会轻微变形并回弹",
    medical: "扭伤最常累及外侧韧带；长期负荷异常也会改变足弓和关节受力。",
    bloodSupply: "胫前、胫后和腓动脉的足踝分支",
    funFact: "双足合计约占全身骨骼数量的四分之一。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "ankle-mortise", label: "踝穴", detail: "胫骨和腓骨远端夹持距骨滑车的骨性结构", position: [0.08, -1.32, -0.55], color: "#ee7c6a" },
      { id: "talus", label: "距骨", detail: "把小腿传来的重量分配给足后部和足中部", position: [0.16, -1.37, -0.52], color: "#6393d8" },
      { id: "calcaneus", label: "跟骨", detail: "足部最大的骨，构成足跟并承接跟腱牵拉", position: [0.14, -1.65, -0.69], color: "#f2a33b" },
      { id: "lateral-ligaments", label: "踝外侧韧带", detail: "距腓前后韧带与跟腓韧带共同抵抗内翻损伤", position: [0, -1.42, -0.6], color: "#d89bc4" },
      { id: "midfoot", label: "足中部", detail: "舟骨、骰骨和三块楔骨连接后足与前足", position: [0.08, -1.5, -0.13], color: "#7fa88a" },
      { id: "metatarsals", label: "跖骨", detail: "五根长骨组成前足的主要支架", position: [-0.06, -1.66, 0.14], color: "#c9956a" },
    ],
  },
  {
    id: "thyroid",
    name: "甲状腺",
    scientificName: "Glandula thyroidea",
    system: "内分泌系统",
    model: "/models/thyroid.glb",
    icon: "⚋",
    accent: "#c98582",
    description: "环抱喉与气管上段前外侧的蝶形内分泌腺，通过甲状腺激素调节能量代谢、生长发育和产热。",
    poetic: "颈前的代谢调音器",
    size: "横径约 5–6 厘米",
    weight: "成人通常约 20–30 克",
    location: "颈前部，甲状软骨下方、气管上段两侧",
    function: "分泌甲状腺激素与降钙素",
    dailyFact: "碘是合成甲状腺激素不可缺少的原料",
    medical: "甲状腺结节很常见，是否需要进一步处理取决于超声特征、功能和细胞学评估。",
    bloodSupply: "甲状腺上动脉与甲状腺下动脉",
    funFact: "左右叶由细窄的峡部相连，整体外形常被比作一只蝴蝶。",
    illustrated: true,
    hotspotSize: 21,
    hotspots: [
      { id: "right-lobe", label: "右叶", detail: "位于气管右侧的主要腺体部分", position: [-1.15, 0.05, 0], color: "#ee7c6a" },
      { id: "left-lobe", label: "左叶", detail: "位于气管左侧的主要腺体部分", position: [1.15, 0.05, 0], color: "#6393d8" },
      { id: "isthmus", label: "峡部", detail: "跨过气管前方并连接左右叶", position: [0, -0.55, 0.9], color: "#f2a33b" },
      { id: "upper-poles", label: "上极", detail: "左右叶向上变窄的部分，邻近甲状软骨", position: [0, 0.95, -0.05], color: "#d89bc4" },
      { id: "lower-poles", label: "下极", detail: "左右叶向下延伸至气管上段两侧", position: [0, -1.05, 0.05], color: "#7fa88a" },
    ],
  },
  {
    id: "pituitary",
    name: "垂体",
    scientificName: "Hypophysis",
    system: "内分泌系统",
    model: "/models/pituitary.glb",
    icon: "●",
    accent: "#b8849c",
    description: "位于颅底蝶鞍内的小型内分泌腺，通过多种促激素协调甲状腺、肾上腺、性腺、生长和水盐平衡。",
    poetic: "蝶鞍中的内分泌枢纽",
    size: "宽约 1 厘米",
    weight: "约 0.5 克",
    location: "颅底蝶鞍内，经垂体柄连接下丘脑",
    function: "整合下丘脑信号并调控多条内分泌轴",
    dailyFact: "它释放的激素会随睡眠、压力和生理周期呈节律变化",
    medical: "垂体病变即使体积很小，也可能引起激素异常或压迫邻近视交叉。",
    bloodSupply: "垂体上、下动脉及垂体门脉系统",
    funFact: "它只有豌豆大小，却能通过激素信号影响全身多个器官。",
    illustrated: true,
    hotspotSize: 22,
    hotspots: [
      { id: "anterior", label: "腺垂体", detail: "分泌生长激素、促甲状腺激素等多种激素的前叶部分", position: [0, -0.45, 0.65], color: "#ee7c6a" },
      { id: "posterior", label: "神经垂体", detail: "储存并释放下丘脑合成的抗利尿激素和催产素", position: [0, 0.55, -0.55], color: "#6393d8" },
      { id: "stalk", label: "垂体柄连接区", detail: "连接下丘脑与垂体的神经和血管通路", position: [0, 1.55, 0], color: "#f2a33b" },
    ],
  },
  {
    id: "parathyroids",
    name: "甲状旁腺",
    scientificName: "Glandulae parathyroideae",
    system: "内分泌系统",
    model: "/models/parathyroids.glb",
    icon: "⁙",
    accent: "#c89a62",
    description: "通常位于甲状腺后方的四枚小型内分泌腺，通过甲状旁腺激素精细调节血钙与磷平衡。",
    poetic: "守护血钙的四枚微小哨兵",
    size: "单枚通常约 3–6 毫米",
    weight: "单枚约 30–40 毫克",
    location: "多位于甲状腺左右叶后方，位置与数量可变",
    function: "分泌甲状旁腺激素并维持钙磷稳态",
    dailyFact: "血钙轻微下降就会迅速促进甲状旁腺激素释放",
    medical: "甲状腺手术时需识别并保护甲状旁腺及其血供，避免术后低钙。",
    bloodSupply: "主要来自甲状腺下动脉分支",
    funFact: "名称相似并不代表功能相同：甲状旁腺与甲状腺是两套不同的内分泌器官。",
    illustrated: true,
    hotspotSize: 24,
    hotspots: [
      { id: "right-superior", label: "右上甲状旁腺", detail: "通常位于右侧甲状腺叶后面较高且较恒定的位置", position: [-1.7, 1.02, -0.13], color: "#ee7c6a" },
      { id: "left-superior", label: "左上甲状旁腺", detail: "通常位于左侧甲状腺叶后面较高的位置", position: [1.7, 1.02, -0.13], color: "#6393d8" },
      { id: "right-inferior", label: "右下甲状旁腺", detail: "位置变化较大，可接近右侧甲状腺下极", position: [-1.13, -1.03, 0.07], color: "#f2a33b" },
      { id: "left-inferior", label: "左下甲状旁腺", detail: "位置变化较大，可接近左侧甲状腺下极", position: [1.13, -1.03, 0.07], color: "#7fa88a" },
    ],
  },
  {
    id: "testis-epididymis",
    name: "睾丸与附睾",
    scientificName: "Testes et epididymides",
    system: "生殖系统",
    model: "/models/testis-epididymis.glb",
    icon: "◉",
    accent: "#b98978",
    description: "睾丸产生精子和雄激素，紧贴其后外侧的附睾则让精子继续成熟、浓缩和储存。",
    poetic: "生殖细胞的生成与成熟站",
    size: "单侧睾丸通常长约 4–5 厘米",
    weight: "单侧约 15–25 克",
    location: "阴囊内，左右各一",
    function: "产生精子与睾酮，并在附睾中完成精子成熟",
    dailyFact: "精子从产生到成熟需要经历连续而漫长的细胞发育过程",
    medical: "突发单侧阴囊剧痛需警惕睾丸扭转，这是一种需要尽快处理的急症。",
    bloodSupply: "睾丸动脉、输精管动脉与提睾肌动脉",
    funFact: "附睾是一条高度盘曲的长管，展开后可达数米。",
    illustrated: false,
    hotspotSize: 21,
    hotspots: [
      { id: "right-testis", label: "右睾丸", detail: "右侧产生精子和雄激素的性腺", position: [-1.26, -0.19, 0.02], color: "#ee7c6a" },
      { id: "right-epididymis", label: "右附睾", detail: "紧贴右睾丸后外侧，参与精子成熟与储存", position: [-1.3, 0.33, -0.13], color: "#f2a33b" },
      { id: "left-testis", label: "左睾丸", detail: "左侧产生精子和雄激素的性腺", position: [1.26, -0.19, 0.02], color: "#6393d8" },
      { id: "left-epididymis", label: "左附睾", detail: "紧贴左睾丸后外侧的盘曲管道", position: [1.3, 0.33, -0.13], color: "#7fa88a" },
      { id: "upper-poles", label: "上极与附睾头", detail: "附睾头通常覆盖睾丸上极附近", position: [0, 0.95, -0.05], color: "#d89bc4" },
      { id: "lower-poles", label: "下极与附睾尾", detail: "附睾尾向下延续为输精管", position: [0, -0.95, -0.05], color: "#c9956a" },
    ],
  },
  {
    id: "salivary-glands",
    name: "大唾液腺",
    scientificName: "Glandulae salivariae majores",
    system: "消化系统",
    model: "/models/salivary-glands.glb",
    icon: "◌",
    accent: "#d19b72",
    description: "腮腺、下颌下腺和舌下腺组成的三对主要唾液腺，经导管向口腔分泌唾液，润滑食物并启动消化。",
    poetic: "口腔消化的清泉",
    size: "腮腺最大，舌下腺最小",
    weight: "双侧腮腺合计约 40–60 克",
    location: "耳前、下颌骨下方与口底",
    function: "分泌唾液，润滑、缓冲并开始淀粉消化",
    dailyFact: "成人每天通常分泌约 1–1.5 升唾液",
    medical: "结石最常阻塞下颌下腺导管，可在进食时引起反复肿痛。",
    bloodSupply: "颈外动脉、面动脉和舌动脉分支",
    funFact: "看到或想到食物就会分泌唾液，是神经系统提前为消化做准备。",
    illustrated: true,
    hotspotSize: 19,
    hotspots: [
      { id: "right-parotid", label: "右腮腺", detail: "位于右耳前和下颌支后方的最大唾液腺", position: [-1.44, 0.36, -0.5], color: "#ee7c6a" },
      { id: "left-parotid", label: "左腮腺", detail: "位于左耳前和下颌支后方", position: [1.44, 0.36, -0.5], color: "#6393d8" },
      { id: "parotid-ducts", label: "腮腺管", detail: "横过咬肌后穿颊肌，开口于上颌第二磨牙对面", position: [0, 0.24, 0.21], color: "#f2a33b" },
      { id: "right-submandibular", label: "右下颌下腺", detail: "位于右侧下颌骨体下方与口底附近", position: [-0.7, -0.73, 0.14], color: "#d89bc4" },
      { id: "left-submandibular", label: "左下颌下腺", detail: "位于左侧下颌骨体下方", position: [0.7, -0.73, 0.14], color: "#c58696" },
      { id: "submandibular-ducts", label: "下颌下腺管", detail: "沿口底向前，开口于舌系带两侧", position: [0, -0.82, 0.42], color: "#7fa88a" },
      { id: "right-sublingual", label: "右舌下腺", detail: "位于右侧口底黏膜下", position: [-0.34, -0.82, 0.67], color: "#c9956a" },
      { id: "left-sublingual", label: "左舌下腺", detail: "位于左侧口底黏膜下", position: [0.34, -0.82, 0.67], color: "#b887a4" },
    ],
  },
  {
    id: "pharynx",
    name: "咽",
    scientificName: "Pharynx",
    system: "呼吸系统",
    model: "/models/pharynx.glb",
    icon: "∫",
    accent: "#b98086",
    description: "从颅底延伸至食管入口的肌性通道，鼻腔、口腔与喉在此交会，是呼吸与吞咽共用的关键路口。",
    poetic: "呼吸与吞咽的十字路口",
    size: "成人长约 12–14 厘米",
    weight: "由黏膜与多层咽肌构成",
    location: "鼻腔、口腔和喉的后方",
    function: "传导空气与食团并协调吞咽",
    dailyFact: "吞咽时软腭和会厌协同，帮助食团进入食管而不是气道",
    medical: "咽部炎症、肿块或神经肌肉异常都可能影响吞咽与呼吸。",
    bloodSupply: "咽升动脉、面动脉与上颌动脉分支",
    funFact: "同一条咽腔既服务呼吸又服务消化，因此吞咽需要精确的时序控制。",
    illustrated: true,
    hotspotSize: 22,
    hotspots: [
      { id: "nasopharynx", label: "鼻咽", detail: "位于鼻腔后方、软腭上方的咽部上段", position: [0, 1.32, -0.28], color: "#6393d8" },
      { id: "oropharynx", label: "口咽", detail: "位于口腔后方，从软腭延伸至会厌上缘附近", position: [0, 0.19, 0.13], color: "#ee7c6a" },
      { id: "laryngopharynx", label: "喉咽", detail: "位于喉后方并向下延续为食管", position: [0, -1.14, -0.6], color: "#7fa88a" },
    ],
  },
  {
    id: "muscular-system",
    name: "全身肌肉系统",
    scientificName: "Systema musculare",
    system: "肌肉系统",
    model: "/models/muscular-system.glb",
    icon: "ϟ",
    accent: "#b75f55",
    description: "覆盖头颈、躯干和四肢的主要表层骨骼肌群，通过跨越关节的收缩产生动作、维持姿势并帮助身体产热。",
    poetic: "牵引身体的红色网络",
    size: "成人骨骼肌约占体重的 30%–40%",
    weight: "随年龄、性别与训练状态差异明显",
    location: "从头颈延伸至躯干和四肢",
    function: "产生运动、维持姿势、稳定关节并产热",
    dailyFact: "站立不动时，许多姿势肌仍在持续进行低强度收缩",
    medical: "此模型选取主要表层肌群用于系统概览；肌肉拉伤、肌腱损伤和神经支配异常都会改变运动能力。",
    bloodSupply: "各区域动脉的肌支",
    funFact: "看似简单的一步行走，需要躯干与双下肢多组肌肉按精确时序协同。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "neck", label: "胸锁乳突肌", detail: "转动、侧屈头颈，并可辅助吸气", position: [-0.08, 1.66, 0.02], color: "#ee7c6a" },
      { id: "chest", label: "胸大肌", detail: "内收、内旋上臂并参与推举动作", position: [-0.28, 1.22, 0.12], color: "#f2a33b" },
      { id: "abdomen", label: "腹直肌", detail: "屈曲躯干并协助维持腹压", position: [-0.1, 0.61, 0.21], color: "#6393d8" },
      { id: "shoulder", label: "三角肌", detail: "包绕肩部，是上臂外展的主要动力之一", position: [-0.52, 1.27, 0.02], color: "#d89bc4" },
      { id: "hip", label: "臀肌群", detail: "稳定骨盆，并参与髋关节伸展与外展", position: [-0.22, 0.15, -0.15], color: "#7fa88a" },
      { id: "thigh", label: "股四头肌", detail: "伸直膝关节并在站立和行走时控制负荷", position: [-0.27, -0.41, 0.07], color: "#c9956a" },
      { id: "calf", label: "小腿前后肌群", detail: "控制踝关节与足部，参与步态推进和落地缓冲", position: [-0.22, -1.35, 0], color: "#b887a4" },
    ],
  },
  {
    id: "skull",
    name: "颅骨",
    scientificName: "Cranium",
    system: "骨骼系统",
    model: "/models/skull.glb",
    icon: "◉",
    accent: "#c69b72",
    description: "由脑颅骨与面颅骨共同构成的复杂骨性框架，保护脑组织，并形成眼眶、鼻腔、口腔和多处肌肉附着面。",
    poetic: "守护感官与思想的骨性穹顶",
    size: "成人颅骨长约 18–22 厘米",
    weight: "通常约 1 千克，个体差异明显",
    location: "脊柱最上端，构成头部骨性支架",
    function: "保护脑、容纳感觉器官并支持咀嚼和发声",
    dailyFact: "多数颅骨通过几乎不活动的骨缝相连",
    medical: "颅底孔道为脑神经和血管提供通路；骨折位置不同，可能影响脑膜、感觉器官或神经血管结构。",
    bloodSupply: "颈外动脉和颈内动脉系统的骨膜与骨内分支",
    funFact: "下颌骨是颅骨中活动度最大的骨，也是唯一通过真正滑膜关节与颅底相连的颅骨。",
    illustrated: true,
    hotspotSize: 20,
    hotspots: [
      { id: "frontal", label: "额骨", detail: "构成前额、眼眶顶和前颅窝的一部分", position: [0, 0.83, 1.03], color: "#ee7c6a" },
      { id: "parietal", label: "顶骨", detail: "左右成对，构成颅顶和颅侧壁的大部分", position: [0.7, 0.72, -0.18], color: "#f2a33b" },
      { id: "temporal", label: "颞骨", detail: "容纳中耳和内耳，并参与颅底与颞下颌关节构成", position: [-0.78, -0.34, -0.03], color: "#6393d8" },
      { id: "sphenoid", label: "蝶骨", detail: "位于颅底中央，连接多块颅骨并容纳垂体窝", position: [0, -0.37, 0.55], color: "#d89bc4" },
      { id: "maxilla", label: "上颌骨", detail: "构成上牙弓、鼻腔外侧壁和眼眶底的一部分", position: [-0.42, -0.56, 1.27], color: "#7fa88a" },
      { id: "mandible", label: "下颌骨", detail: "承载下牙列并通过颞下颌关节完成开闭口运动", position: [0, -1.18, 0.85], color: "#c9956a" },
      { id: "occipital", label: "枕骨", detail: "构成颅后部和后颅窝，并以枕骨大孔连接椎管", position: [0, -0.02, -0.82], color: "#b887a4" },
    ],
  },
  {
    id: "spine",
    name: "脊柱",
    scientificName: "Columna vertebralis",
    system: "骨骼系统",
    model: "/models/spine.glb",
    icon: "≀",
    accent: "#b99a78",
    description: "由颈椎、胸椎、腰椎以及骶尾骨连接形成的纵向支柱，承托头和躯干，同时以椎管保护脊髓。",
    poetic: "身体中央的弹性支柱",
    size: "成人全长约 70 厘米",
    weight: "由 33 块左右椎骨及其连接结构共同构成",
    location: "从颅底延伸至骨盆后部",
    function: "承重、保护脊髓并允许躯干多方向活动",
    dailyFact: "椎间盘在白天受压，身高可因此比清晨略低",
    medical: "正常生理曲度可分散负荷；骨折、退变或椎管狭窄可能影响稳定性与神经结构。",
    bloodSupply: "椎动脉、肋间后动脉、腰动脉和骶外侧动脉分支",
    funFact: "颈椎只有七块，却需要同时兼顾头部支撑与很大的活动范围。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "atlas-axis", label: "寰椎与枢椎", detail: "支撑颅骨并完成大部分点头与转头运动", position: [0, 1.82, 0.04], color: "#ee7c6a" },
      { id: "cervical", label: "颈椎", detail: "七块椎骨构成灵活的颈段", position: [0, 1.55, 0.08], color: "#f2a33b" },
      { id: "thoracic", label: "胸椎", detail: "十二块椎骨与肋骨相连，共同构成胸廓后壁", position: [0, 0.5, -0.13], color: "#6393d8" },
      { id: "lumbar", label: "腰椎", detail: "五块较大的椎骨承担躯干大部分负荷", position: [0, -0.78, 0.1], color: "#d89bc4" },
      { id: "sacrum", label: "骶骨", detail: "融合的骶椎把脊柱负荷传递至骨盆", position: [0, -1.41, -0.05], color: "#7fa88a" },
      { id: "coccyx", label: "尾骨", detail: "位于脊柱末端，为盆底肌和韧带提供附着", position: [0, -1.82, -0.08], color: "#c9956a" },
    ],
  },
  {
    id: "hand-wrist",
    name: "手与腕",
    scientificName: "Manus et carpus",
    system: "骨骼系统",
    model: "/models/hand-wrist.glb",
    icon: "✋",
    accent: "#c18e70",
    description: "由桡尺骨远端、八块腕骨、五块掌骨、指骨以及精细的肌腱、韧带和关节共同组成的灵巧执行器。",
    poetic: "把意图变成动作的精密工具",
    size: "单手通常有 27 块骨",
    weight: "约占体重的 0.5% 左右",
    location: "前臂远端至五指末端",
    function: "抓握、捏持、触摸并完成精细操作",
    dailyFact: "拇指对掌让指腹能够与其他手指相对，是精细抓握的基础",
    medical: "腕管内空间有限，正中神经受压可引起拇、示、中指区域麻木和手部无力。",
    bloodSupply: "桡动脉与尺动脉形成的掌浅弓、掌深弓及其分支",
    funFact: "八块腕骨排成两列，在很小空间内共同完成屈伸、偏斜和负荷传递。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "radius-ulna", label: "桡尺骨远端", detail: "构成前臂与腕部的骨性连接和旋转基础", position: [0.2, 1.62, -0.66], color: "#ee7c6a" },
      { id: "scaphoid", label: "舟骨", detail: "位于腕骨近列桡侧，骨折后需关注血供", position: [0.2, 1.28, -0.57], color: "#f2a33b" },
      { id: "lunate", label: "月骨", detail: "位于腕骨近列中央，参与桡腕关节构成", position: [0.56, 1.28, -0.57], color: "#6393d8" },
      { id: "capitate", label: "头状骨", detail: "腕骨中最大的一块，位于远列中央", position: [0.3, 1.06, -0.55], color: "#d89bc4" },
      { id: "thumb", label: "拇指骨列", detail: "第一掌骨和两节指骨形成高度灵活的拇指", position: [-0.43, 0.76, -0.14], color: "#7fa88a" },
      { id: "metacarpals", label: "掌骨", detail: "五块掌骨构成手掌的主要骨性支架", position: [0.17, 0.5, -0.18], color: "#c9956a" },
      { id: "phalanges", label: "指骨", detail: "除拇指外每指三节，完成精细屈伸与抓握", position: [0.2, -0.7, 0.18], color: "#b887a4" },
    ],
  },
  {
    id: "rotator-cuff",
    name: "旋转袖（右侧参考）",
    scientificName: "Musculi cuffiae rotatoriae dextrae",
    system: "肌肉系统",
    model: "/models/rotator-cuff.glb",
    icon: "◔",
    accent: "#b96f63",
    description: "由冈上肌、冈下肌、小圆肌和肩胛下肌的肌腱共同包绕肱骨头，动态稳定肩关节并引导上臂旋转。",
    poetic: "包住肩关节的四肌护套",
    size: "覆盖肩胛骨前后面并汇聚于肱骨近端",
    weight: "由四块肌及其肌腱共同构成",
    location: "右侧肩胛骨与肱骨头周围",
    function: "稳定肱骨头并参与肩外展、内旋和外旋",
    dailyFact: "抬手时旋转袖会持续微调肱骨头，使其保持在较浅的关节盂中央",
    medical: "退变、撞击或急性负荷都可能造成肌腱病或撕裂，症状常表现为肩痛和抬臂无力。",
    bloodSupply: "肩胛上动脉、肩胛下动脉和旋肱动脉分支",
    funFact: "旋转袖的“袖”并不是一块独立结构，而是四条肌腱在关节囊周围融合形成的功能整体。",
    illustrated: true,
    hotspotSize: 20,
    hotspots: [
      { id: "supraspinatus", label: "冈上肌", detail: "启动肩外展并压稳肱骨头", position: [0, 1.57, -0.26], color: "#ee7c6a" },
      { id: "infraspinatus", label: "冈下肌", detail: "主要使上臂外旋，并稳定关节后方", position: [-0.01, 0.96, -0.39], color: "#6393d8" },
      { id: "teres-minor", label: "小圆肌", detail: "协助上臂外旋与内收", position: [-0.24, 0.91, -0.32], color: "#f2a33b" },
      { id: "subscapularis", label: "肩胛下肌", detail: "位于肩胛骨前面，主要使上臂内旋", position: [0.05, 0.89, -0.22], color: "#d89bc4" },
      { id: "humeral-head", label: "肱骨头", detail: "四条肌腱围绕并稳定的球形关节面", position: [-0.75, 1.02, -0.1], color: "#7fa88a" },
      { id: "scapula", label: "肩胛骨", detail: "为四块旋转袖肌提供主要起点", position: [0.35, 0.9, -0.35], color: "#c9956a" },
    ],
  },
  {
    id: "brachial-plexus",
    name: "臂丛神经（右侧参考）",
    scientificName: "Plexus brachialis dexter",
    system: "神经系统",
    model: "/models/brachial-plexus.glb",
    icon: "⋉",
    accent: "#d5a449",
    viewScale: 1.1,
    description: "由 C5 至 T1 脊神经前支编织而成的神经网络，经根、干、股、束逐级重组后，为肩带和上肢提供运动与感觉支配。",
    poetic: "从颈部通向手指的信号编织",
    size: "从颈根延伸至腋窝并继续进入整条上肢",
    weight: "由多条神经纤维束组成",
    location: "右侧下颈部、锁骨后方与腋窝内",
    function: "传递上肢运动命令与感觉信息",
    dailyFact: "同一根终末神经通常混合来自多个脊髓节段的纤维",
    medical: "牵拉、压迫或穿透伤可在不同层级损伤臂丛，产生具有定位意义的肌力和感觉缺失模式。",
    bloodSupply: "锁骨下动脉与腋动脉周围分支形成的神经营养血管",
    funFact: "臂丛会先把五条神经根重新组合，再分成主要终末神经进入上肢。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "roots", label: "C5–T1 神经根", detail: "五条脊神经前支构成臂丛的起点", position: [0.63, 1.63, 0.14], color: "#ee7c6a" },
      { id: "trunks", label: "上、中、下干", detail: "神经根在颈部重组为三条神经干", position: [0.45, 1.48, 0.15], color: "#f2a33b" },
      { id: "divisions", label: "前后股", detail: "三干在锁骨后方各分成前股和后股", position: [0.25, 1.38, 0.13], color: "#6393d8" },
      { id: "cords", label: "臂丛三束", detail: "外侧束、内侧束与后束围绕腋动脉排列，并发出终末分支", position: [0.08, 1.22, 0.13], color: "#d89bc4" },
      { id: "median", label: "正中神经", detail: "支配多数前臂屈肌，并传递手掌桡侧感觉", position: [-0.01, 0.35, 0.12], color: "#7fa88a" },
      { id: "ulnar", label: "尺神经", detail: "支配多数组手内在肌并传递手尺侧感觉", position: [0.12, -0.25, 0.06], color: "#c9956a" },
      { id: "radial", label: "桡神经", detail: "支配上肢后群伸肌并传递相应皮肤感觉", position: [-0.18, 0.1, -0.02], color: "#b887a4" },
    ],
  },
  {
    id: "brainstem-cerebellum",
    name: "脑干与小脑",
    scientificName: "Truncus encephali et cerebellum",
    system: "神经系统",
    model: "/models/brainstem-cerebellum.glb",
    icon: "◒",
    accent: "#b57d91",
    description: "脑干连接大脑、脊髓和多条脑神经，小脑则持续整合感觉与运动信息，共同维持清醒、呼吸、平衡和动作协调。",
    poetic: "生命节律与动作校准的交汇处",
    size: "小脑横径约 10 厘米，脑干长约 7–8 厘米",
    weight: "小脑约占全脑重量的 10%",
    location: "颅后窝内，大脑半球后下方",
    function: "维持生命反射、传递神经信号并协调运动",
    dailyFact: "小脑虽然体积不大，却容纳了全脑一半以上的神经元",
    medical: "脑干病变可能同时影响意识、呼吸和多条脑神经；小脑损伤常表现为共济失调、眼震或构音障碍。",
    bloodSupply: "椎-基底动脉系统及其小脑动脉分支",
    funFact: "小脑不会直接发起多数随意运动，却会像实时校准器一样修正动作的力度、方向和时序。",
    illustrated: true,
    hotspotSize: 19,
    hotspots: [
      { id: "midbrain", label: "中脑", detail: "脑干上段，参与眼球运动、听视觉反射和运动调控", position: [0.07, 0.88, 0.81], color: "#ee7c6a" },
      { id: "pons", label: "脑桥", detail: "连接大脑、小脑与延髓，并参与呼吸节律和多条脑神经功能", position: [0.05, 0.12, 0.92], color: "#f2a33b" },
      { id: "medulla", label: "延髓", detail: "含有调节呼吸、循环和吞咽等生命活动的重要中枢", position: [0.02, -0.72, 0.72], color: "#6393d8" },
      { id: "vermis", label: "小脑蚓部", detail: "位于两侧小脑半球之间，主要协调躯干与姿势控制", position: [0, 0.15, -0.34], color: "#d89bc4" },
      { id: "hemispheres", label: "小脑半球", detail: "参与四肢动作的精确控制、运动学习与时序调整", position: [1.18, -0.31, -0.24], color: "#7fa88a" },
      { id: "deep-nuclei", label: "小脑深部核团", detail: "整合小脑皮质输出，并将校准后的信号送往脑干和丘脑", position: [0.38, -0.07, -0.04], color: "#c9956a" },
      { id: "peduncles", label: "小脑脚", detail: "三对纤维束把小脑与中脑、脑桥和延髓相连", position: [0.62, -0.05, 0.52], color: "#b887a4" },
    ],
  },
  {
    id: "coronary-circulation",
    name: "冠状循环（女性参考）",
    scientificName: "Circulatio coronaria",
    system: "心血管系统",
    model: "/models/coronary-circulation.glb",
    icon: "⌁",
    accent: "#c9605b",
    description: "分布在心脏表面的冠状动脉为心肌供氧，伴行静脉再把血液汇入冠状窦并返回右心房；本模型采用 HuBMAP 女性参考坐标。",
    poetic: "滋养不眠之泵的环形河网",
    size: "主要血管沿心脏表面和冠状沟分布",
    weight: "由细小而高度分支的血管网络构成",
    location: "心外膜下及心肌内",
    function: "为心肌输送氧和营养并回收静脉血",
    dailyFact: "心肌几乎持续工作，因此静息时也需要稳定而丰富的冠状血流",
    medical: "冠状动脉粥样硬化或急性血栓可减少心肌供血，引起心绞痛或心肌梗死。",
    bloodSupply: "左冠状动脉与右冠状动脉",
    funFact: "冠状血流主要在心室舒张期进入心肌，因为收缩期的心肌会挤压其中的小血管。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "left-coronary", label: "左冠状动脉主干", detail: "从主动脉根部发出，短行后通常分为前降支和回旋支", position: [-0.35, 0.54, 0], color: "#ee7c6a" },
      { id: "lad", label: "前降支", detail: "沿前室间沟下行，供应室间隔前部和左心室前壁", position: [0.51, -0.26, 0.52], color: "#f2a33b" },
      { id: "circumflex", label: "回旋支", detail: "沿左侧冠状沟绕向心脏后方，供应左心房和左心室侧后壁", position: [-0.14, 0.39, -0.55], color: "#d89bc4" },
      { id: "right-coronary", label: "右冠状动脉", detail: "沿右侧冠状沟走行，并发出供应右心的多个分支", position: [-0.69, -0.59, -0.08], color: "#6393d8" },
      { id: "right-marginal", label: "右缘支", detail: "沿心脏锐缘走行，主要供应右心室游离壁", position: [-0.5, -1.33, 0.99], color: "#7fa88a" },
      { id: "great-cardiac-vein", label: "心大静脉", detail: "多伴随前降支走行，把前壁静脉血导向冠状窦", position: [0.52, -0.11, 0.07], color: "#b887a4" },
      { id: "coronary-sinus", label: "冠状窦", detail: "心脏静脉血的主要汇集通道，开口于右心房", position: [-0.4, -0.65, -0.74], color: "#6f8fba" },
    ],
  },
  {
    id: "sciatic-nerve",
    name: "坐骨神经（右侧参考）",
    scientificName: "Nervus ischiadicus dexter",
    system: "神经系统",
    model: "/models/sciatic-nerve.glb",
    icon: "⌇",
    accent: "#d1a346",
    description: "人体最粗大的周围神经，从骶丛离开骨盆，经臀部和大腿后方下行，在腘窝附近分为胫神经与腓总神经。",
    poetic: "从骨盆延伸到足部的长程信号缆",
    size: "主干可接近拇指粗细，跨越臀部至大腿远端",
    weight: "由 L4–S3 神经纤维共同组成",
    location: "右侧臀深部、大腿后方及小腿分支区域",
    function: "支配大腿后群及小腿足部，并传递广泛感觉信息",
    dailyFact: "走路、屈膝、踝足运动和足底感觉都依赖其不同分支",
    medical: "腰骶神经根或坐骨神经受刺激可产生沿臀部和下肢放射的疼痛、麻木或无力。",
    bloodSupply: "下臀动脉、穿动脉及伴行神经营养血管",
    funFact: "坐骨神经在一个共同外膜内同时携带胫神经和腓总神经两套纤维，二者可在不同高度分开。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "piriformis", label: "梨状肌出口", detail: "坐骨神经通常从梨状肌下方离开骨盆进入臀区", position: [-0.14, 1.4, -0.08], color: "#ee7c6a" },
      { id: "sciatic-trunk", label: "坐骨神经主干", detail: "在臀大肌深面和大腿后群之间向下走行", position: [-0.1, 0.95, -0.1], color: "#f2a33b" },
      { id: "bifurcation", label: "胫神经与腓总神经分叉", detail: "通常在腘窝上方或其内分成两大终末支", position: [-0.1, 0.42, -0.09], color: "#d89bc4" },
      { id: "tibial", label: "胫神经", detail: "沿小腿后群下行，继续进入足底", position: [-0.11, -0.02, -0.14], color: "#6393d8" },
      { id: "common-fibular", label: "腓总神经", detail: "向腓骨颈外侧绕行后分为浅、深腓神经", position: [-0.1, 0.67, -0.05], color: "#7fa88a" },
      { id: "superficial-fibular", label: "腓浅神经", detail: "支配小腿外侧群，并传递足背大部分皮肤感觉", position: [-0.29, -1.1, -0.09], color: "#c9956a" },
      { id: "deep-fibular", label: "腓深神经", detail: "支配小腿前群，并传递第一趾蹼区域感觉", position: [-0.23, -1.18, -0.01], color: "#b887a4" },
    ],
  },
  {
    id: "cranial-nerves",
    name: "脑神经",
    scientificName: "Nervi craniales",
    system: "神经系统",
    model: "/models/cranial-nerves.glb",
    icon: "✣",
    accent: "#caa042",
    description: "十二对脑神经直接连接脑和脑干，承担嗅觉、视觉、听觉、平衡、面部感觉与运动、吞咽以及内脏副交感调节。",
    poetic: "从颅底伸向感官与内脏的十二条通路",
    size: "从短小的嗅、视通路到延伸至胸腹部的迷走神经",
    weight: "由感觉、运动或混合神经纤维组成",
    location: "脑和脑干腹侧发出，经颅底孔道分布至头颈及部分胸腹器官",
    function: "连接感官、头颈运动、吞咽发声与自主神经活动",
    dailyFact: "只有迷走神经会广泛延伸到胸腔和腹腔器官",
    medical: "眼位、瞳孔、面部感觉与表情、听力、吞咽和舌运动检查可帮助定位不同脑神经受损。",
    bloodSupply: "椎-基底动脉与颈内、颈外动脉系统的神经营养分支",
    funFact: "十二对脑神经按从前向后的出脑顺序编号，而不是按大小或功能分类。",
    illustrated: true,
    hotspotSize: 16,
    hotspots: [
      { id: "cn-i", label: "I 嗅神经", detail: "把鼻腔嗅觉感受器的信号传向嗅球和嗅束", position: [0.06, 1.32, 0.36], color: "#ee7c6a" },
      { id: "cn-ii", label: "II 视神经", detail: "传递视网膜信号，并在视交叉处部分交叉", position: [0.08, 1.29, 0.34], color: "#f2a33b" },
      { id: "cn-iii", label: "III 动眼神经", detail: "支配多数眼外肌、提上睑肌和瞳孔缩小", position: [0.11, 1.23, 0.28], color: "#6393d8" },
      { id: "cn-iv", label: "IV 滑车神经", detail: "支配上斜肌，是唯一从脑干背侧发出的脑神经", position: [0.08, 1.29, 0.22], color: "#d89bc4" },
      { id: "cn-v", label: "V 三叉神经", detail: "传递面部感觉，并支配咀嚼肌", position: [0.08, 1.21, 0.08], color: "#7fa88a" },
      { id: "cn-vi", label: "VI 展神经", detail: "支配外直肌，使眼球向外转动", position: [0.1, 1.2, 0.18], color: "#c9956a" },
      { id: "cn-vii", label: "VII 面神经", detail: "控制面部表情，并传递舌前部味觉等信号", position: [0.2, 1.07, 0.31], color: "#b887a4" },
      { id: "cn-viii", label: "VIII 前庭蜗神经", detail: "传递听觉和头部运动、平衡信息", position: [0.08, 1.15, 0.02], color: "#6f8fba" },
      { id: "cn-ix", label: "IX 舌咽神经", detail: "参与咽部感觉、舌后部味觉和吞咽", position: [0.12, 0.66, 0.12], color: "#cf7f6e" },
      { id: "cn-x", label: "X 迷走神经", detail: "参与吞咽发声，并向胸腹部器官提供广泛副交感支配", position: [0.09, 0.39, 0.05], color: "#7b9b83" },
      { id: "cn-xi", label: "XI 副神经", detail: "主要支配胸锁乳突肌和斜方肌", position: [0.19, 0.19, -0.24], color: "#b88961" },
      { id: "cn-xii", label: "XII 舌下神经", detail: "支配大多数舌肌，参与构音和吞咽", position: [0.08, 0.91, 0.19], color: "#9a7da9" },
    ],
  },
  {
    id: "pelvic-floor-perineum",
    name: "盆底与会阴（男性右侧参考）",
    scientificName: "Diaphragma pelvis et perineum masculinum",
    system: "肌肉系统",
    model: "/models/pelvic-floor-perineum.glb",
    icon: "⌣",
    accent: "#b87870",
    description: "盆底肌、会阴膜和筋膜共同封闭骨盆下口，承托盆腔器官并参与控尿、排便和腹压调节；模型为男性右侧区域参考。",
    poetic: "托住盆腔的肌性吊床",
    size: "跨越耻骨、坐骨和尾骨之间的骨盆下口",
    weight: "由多层肌肉、筋膜、韧带与神经共同构成",
    location: "骨盆最下方，会阴区域上方",
    function: "承托盆腔器官并参与控尿、排便和核心稳定",
    dailyFact: "咳嗽、跳跃或搬重物时，盆底会与膈肌和腹壁协同调节腹压",
    medical: "盆底肌损伤或神经功能异常可能导致失禁、盆腔器官支持不足或慢性盆底疼痛。",
    bloodSupply: "阴部内动脉、臀下动脉及其分支",
    funFact: "提肛肌并非一整块肌肉，而是由髂尾肌、耻骨尾骨肌和耻骨直肠肌等部分共同组成。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "iliococcygeus", label: "髂尾肌", detail: "提肛肌的外侧部分，参与形成盆底肌性支撑", position: [0.22, -0.91, -0.19], color: "#ee7c6a" },
      { id: "puborectalis", label: "耻骨直肠肌与耻骨尾骨肌", detail: "围绕肛直肠连接区并参与维持控便角度", position: [0.39, -1.36, -0.1], color: "#f2a33b" },
      { id: "coccygeus", label: "尾骨肌", detail: "位于盆膈后部，连接坐骨棘与骶尾骨", position: [0.18, -0.56, -0.73], color: "#6393d8" },
      { id: "anal-sphincter", label: "肛门外括约肌", detail: "由深、浅和皮下部分共同参与随意控便", position: [0.63, -1.53, -0.47], color: "#d89bc4" },
      { id: "perineal-membrane", label: "会阴膜", detail: "横跨前方会阴三角，为相关肌和勃起组织提供支持", position: [0.63, -1.52, 0.18], color: "#7fa88a" },
      { id: "pudendal-nerve", label: "阴部神经", detail: "为会阴皮肤和多块括约肌提供主要躯体感觉与运动支配", position: [0.13, -0.56, -0.07], color: "#c9956a" },
      { id: "pudendal-canal", label: "阴部管", detail: "阴部神经和血管沿闭孔内肌筋膜形成的通道前行", position: [-0.09, -1.25, -0.39], color: "#b887a4" },
    ],
  },
  {
    id: "inguinal-canal",
    name: "腹股沟管（男性右侧参考）",
    scientificName: "Canalis inguinalis dexter masculinus",
    system: "运动系统",
    model: "/models/inguinal-canal.glb",
    icon: "⋰",
    accent: "#b88a68",
    description: "腹股沟区由腹外斜肌、腹内斜肌、腹横肌及多条韧带共同形成斜行通道；模型展示男性右侧参考及输精管走行。",
    poetic: "穿过下腹壁的斜行通道",
    size: "成人腹股沟管长约 4 厘米",
    weight: "由腹壁层次、筋膜和韧带围成",
    location: "右侧腹股沟韧带内侧半上方",
    function: "为男性精索相关结构穿过腹壁提供通道",
    dailyFact: "站立、咳嗽和用力时腹压升高，腹股沟区需要多层结构协同维持关闭",
    medical: "腹股沟区薄弱或通道关闭机制失衡可形成腹股沟疝，需结合体检和影像判断类型。",
    bloodSupply: "腹壁下动脉、旋髂深动脉和阴部外动脉分支",
    funFact: "腹股沟管不是一根独立的管子，而是腹壁不同层次错位重叠后形成的潜在通道。",
    illustrated: true,
    hotspotSize: 19,
    hotspots: [
      { id: "inguinal-ligament", label: "腹股沟韧带", detail: "腹外斜肌腱膜下缘增厚，连接髂前上棘与耻骨结节", position: [0.06, 0.17, 0.31], color: "#ee7c6a" },
      { id: "superficial-ring", label: "腹股沟浅环", detail: "由腹外斜肌腱膜内、外侧脚围成的出口", position: [0.62, -0.55, 0.37], color: "#f2a33b" },
      { id: "abdominal-wall", label: "腹壁肌层", detail: "腹外斜肌、腹内斜肌与腹横肌共同构成通道周围的动态支撑", position: [0.04, 0.68, 0.3], color: "#6393d8" },
      { id: "iliopubic-tract", label: "髂耻束", detail: "腹横筋膜下缘增厚，位于腹股沟韧带深面", position: [0.06, 0.09, 0.26], color: "#d89bc4" },
      { id: "lacunar-ligament", label: "腔隙韧带", detail: "腹股沟韧带内侧端向后附着于耻骨梳的纤维结构", position: [0.48, -0.45, 0.27], color: "#7fa88a" },
      { id: "pectineal-ligament", label: "耻骨梳韧带", detail: "沿耻骨梳走行，是腹股沟后方重要的坚韧附着结构", position: [0.34, -0.31, 0.14], color: "#c9956a" },
      { id: "ductus-deferens", label: "输精管", detail: "男性精索的重要组成，穿过腹股沟管进入盆腔", position: [0.54, -1.03, -0.2], color: "#b887a4" },
    ],
  },
  {
    id: "tmj",
    name: "颞下颌关节（右侧参考）",
    scientificName: "Articulatio temporomandibularis dextra",
    system: "运动系统",
    model: "/models/tmj.glb",
    icon: "⊏",
    accent: "#c99a6b",
    viewScale: 1.5,
    description: "由下颌头、颞骨关节面和关节盘构成的联动关节，配合咀嚼肌完成张口、咀嚼和说话；模型为右侧参考，并保留下颌骨与颞骨作为空间参照。",
    poetic: "每天开合数千次的精密铰链",
    size: "关节盘直径约 2 厘米，是全身最精细的关节之一",
    weight: "由关节盘、关节囊、韧带与咀嚼肌共同协作",
    location: "耳屏前方，下颌骨髁突与颞骨关节窝之间",
    function: "完成张口闭口、前伸和侧方研磨运动",
    dailyFact: "说话、咀嚼和吞咽时它几乎不停工作，是全身使用频率最高的关节之一",
    medical: "关节弹响、张口受限或咀嚼疼痛可能提示颞下颌关节紊乱，常与咬合、精神紧张和不良习惯相关。",
    bloodSupply: "颞浅动脉与上颌动脉分支",
    funFact: "张口时下颌头不只是原地转动，还会带着关节盘一起向前滑动到关节结节下方。",
    illustrated: true,
    hotspotSize: 16,
    hotspots: [
      { id: "disc", label: "关节盘", detail: "分隔下颌头与颞骨的纤维软骨盘，随张口向前滑动", position: [-0.97, 0.43, -0.23], color: "#6393d8" },
      { id: "capsule", label: "关节囊", detail: "包裹关节的纤维囊，内衬滑膜并分泌滑液", position: [-1.32, 0.53, -0.16], color: "#7fa88a" },
      { id: "lateral-ligament", label: "颞下颌韧带", detail: "加强关节囊外侧，限制下颌过度后退和外移", position: [-1.2, 0.24, -0.07], color: "#f2a33b" },
      { id: "condyle", label: "下颌头（髁突）", detail: "下颌骨的关节突起，张口时向前下方滑动", position: [-0.91, 0.53, -0.28], color: "#ee7c6a" },
      { id: "fossa", label: "颞骨关节面", detail: "关节窝与关节结节构成关节的上半，关节盘在其下方滑动", position: [-0.94, 0.61, -0.34], color: "#b887a4" },
    ],
  },
  {
    id: "intervertebral-discs",
    name: "椎间盘",
    scientificName: "Disci intervertebrales",
    system: "运动系统",
    model: "/models/intervertebral-discs.glb",
    icon: "≡",
    accent: "#7d9cc4",
    description: "位于相邻椎体之间的纤维软骨垫，由外周纤维环和中央髓核组成，缓冲震荡并允许脊柱屈伸旋转；模型展示 C2–S1 全部椎间盘及主要纵韧带，并保留椎骨作为空间参照。",
    poetic: "脊柱的减震垫圈",
    size: "共 23 个，合计约占脊柱全长的四分之一",
    weight: "外周为纤维环，中央为胶冻状髓核",
    location: "第 2 颈椎至骶骨之间的相邻椎体间",
    function: "缓冲垂直负荷、维持椎间隙高度并参与脊柱活动",
    dailyFact: "晨起时身高比睡前高约 1–2 厘米，部分来自椎间盘夜间吸水回弹",
    medical: "纤维环破裂、髓核突出可能压迫邻近神经根，引起颈肩或腰腿放射痛，以 L4–L5 和 L5–S1 节段最常见。",
    bloodSupply: "成人椎间盘中央基本无血管，主要依靠椎体终板扩散获取营养",
    funFact: "椎间盘是全身最大的无血管结构之一，营养供给依赖日常活动产生的压力泵效应。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "cervical-disc", label: "颈椎间盘（C5–C6）", detail: "颈段椎间盘较薄，适应颈椎灵活的前屈后伸和旋转", position: [0, 1.44, 0.17], color: "#6393d8" },
      { id: "lumbar-disc", label: "腰椎间盘（L4–L5）", detail: "承重最大的椎间盘之一，也是椎间盘突出的高发节段", position: [0, -1.18, 0.31], color: "#ee7c6a" },
      { id: "anterior-longitudinal", label: "前纵韧带", detail: "贴附椎体前方，限制脊柱过度后伸", position: [0, -0.94, 0.34], color: "#f2a33b" },
      { id: "posterior-longitudinal", label: "后纵韧带", detail: "位于椎体后方、椎管前壁，限制脊柱过度前屈", position: [0.05, 0.47, -0.15], color: "#7fa88a" },
      { id: "interspinous", label: "棘间韧带", detail: "连接相邻棘突，协助限制前屈", position: [0, 0.89, -0.33], color: "#d89bc4" },
      { id: "supraspinous", label: "棘上韧带", detail: "沿棘突尖走行的长韧带，腰椎穿刺时逐层穿过", position: [0, 1.34, -0.18], color: "#c9956a" },
    ],
  },
  {
    id: "median-nerve",
    name: "正中神经（右侧参考）",
    scientificName: "Nervus medianus dexter",
    system: "神经系统",
    model: "/models/median-nerve.glb",
    icon: "⋉",
    accent: "#d5a24a",
    description: "由臂丛内、外侧束的两个根汇合而成，沿臂部、肘窝和前臂正中下行，经腕管进入手掌；模型为右侧参考，保留肱骨、桡尺骨作为行程参照。",
    poetic: "手掌感觉与抓握的主干电缆",
    size: "自腋区延伸至指尖，是上肢最长的神经干之一",
    weight: "由 C5–T1 神经根纤维经内、外侧束汇合组成",
    location: "右侧腋区经臂、肘窝、前臂正中至手掌",
    function: "支配前臂多数屈肌与鱼际肌，传递手掌桡侧半感觉",
    dailyFact: "拧毛巾、握笔和系扣都依赖正中神经支配的屈肌与鱼际肌协同",
    medical: "腕管内受压形成腕管综合征，表现为拇指至中指麻木、夜间麻醒，是最常见的周围神经卡压症。",
    bloodSupply: "肱动脉、尺动脉等伴行血管的神经营养分支",
    funFact: "正中神经在臂部不发出任何分支，直到前臂才开始分支，因此肘以上损伤主要表现为手腕和手指症状。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "roots", label: "内、外侧根", detail: "分别从臂丛内、外侧束发出，在腋动脉前方汇合成本干", position: [0.37, 1.58, 0.03], color: "#ee7c6a" },
      { id: "arm-course", label: "臂部行程", detail: "与肱动脉伴行，沿臂内侧下行，此段不发分支", position: [0.19, 1.04, -0.02], color: "#6393d8" },
      { id: "cubital", label: "肘窝与旋前圆肌", detail: "经肘窝穿旋前圆肌两头之间进入前臂", position: [-0.2, -0.61, 0.08], color: "#f2a33b" },
      { id: "carpal-tunnel", label: "腕管", detail: "与九条屈肌腱共同穿过腕横韧带下方的骨纤维管道", position: [-0.4, -1.46, 0.19], color: "#7fa88a" },
      { id: "palmar-branches", label: "手掌分支", detail: "支配鱼际肌，并传递桡侧三个半手指的掌面感觉", position: [-0.52, -1.9, 0.33], color: "#d89bc4" },
    ],
  },
  {
    id: "ulnar-nerve",
    name: "尺神经（右侧参考）",
    scientificName: "Nervus ulnaris dexter",
    system: "神经系统",
    model: "/models/ulnar-nerve.glb",
    icon: "⋊",
    accent: "#c08d5d",
    description: "由臂丛内侧束延续而来，绕经肱骨内上髁后方的尺神经沟，沿前臂尺侧下行入手；模型为右侧参考，保留肱骨、桡尺骨作为行程参照。",
    poetic: "绕过“麻筋”的那根神经",
    size: "自腋区延伸至小指，是手内在肌的主要支配者",
    weight: "主要携带 C8–T1 神经根纤维",
    location: "右侧腋区经臂内侧、肘后尺神经沟、前臂尺侧至手掌",
    function: "支配大部分手内在肌，传递小指与环指尺侧半感觉",
    dailyFact: "写字时手指的精细捏合与夹纸动作，主要靠尺神经支配的手内在肌完成",
    medical: "尺神经沟处长期受压或肘外翻可致尺神经病变，表现为小指、环指麻木，重者出现爪形手。",
    bloodSupply: "尺侧上副动脉、尺动脉及其伴行分支",
    funFact: "撞到“麻筋”时从肘部窜到小指的过电感，其实就是尺神经在尺神经沟处被撞击。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "medial-cord", label: "臂丛内侧束", detail: "尺神经是内侧束的直接延续，纤维主要来自 C8–T1", position: [0.2, 1.54, 0.05], color: "#ee7c6a" },
      { id: "arm-course", label: "臂内侧段", detail: "沿肱动脉内侧下行，后穿内侧肌间隔进入臂后区", position: [-0.05, 1.03, -0.02], color: "#6393d8" },
      { id: "ulnar-groove", label: "尺神经沟（肘管）", detail: "绕经肱骨内上髁后方，位置表浅，是“麻筋”所在", position: [-0.28, -0.22, -0.24], color: "#f2a33b" },
      { id: "forearm-course", label: "前臂尺侧段", detail: "行于尺侧腕屈肌深面，与尺动脉伴行", position: [-0.4, -1.01, 0.05], color: "#7fa88a" },
      { id: "guyon-canal", label: "腕尺管", detail: "经豌豆骨与钩骨之间的 Guyon 管进入手掌", position: [-0.52, -1.45, 0.16], color: "#d89bc4" },
      { id: "hand-branches", label: "手部深、浅支", detail: "深支支配多数手内在肌，浅支传递尺侧皮肤感觉", position: [-0.61, -1.86, 0.31], color: "#b887a4" },
    ],
  },
  {
    id: "radial-nerve",
    name: "桡神经（右侧参考）",
    scientificName: "Nervus radialis dexter",
    system: "神经系统",
    model: "/models/radial-nerve.glb",
    icon: "⋈",
    accent: "#c99a3e",
    description: "臂丛后束的最大分支，绕肱骨桡神经沟螺旋下行，在肘部分为浅、深两支，支配臂与前臂全部伸肌；模型为右侧参考，保留肱骨与肱三头肌作为行程参照。",
    poetic: "绕肱骨螺旋而下的伸肌总开关",
    size: "自腋区绕肱骨后方向下，分支遍布整个伸侧",
    weight: "主要携带 C5–T1 神经根纤维，经后束发出",
    location: "右侧腋区经肱骨桡神经沟、肘外侧至前臂后区与手背",
    function: "支配肱三头肌与前臂伸肌群，传递臂、前臂背面及手背桡侧感觉",
    dailyFact: "伸腕、伸指、竖大拇指，都由桡神经支配的肌肉完成",
    medical: "肱骨干骨折或腋杖长期压迫可损伤桡神经，典型表现为腕下垂（垂腕征）。",
    bloodSupply: "肱深动脉、桡侧副动脉等伴行血管的神经营养分支",
    funFact: "“周末夜麻痹”——沉睡或醉酒后上臂长时间受压，桡神经暂时罢工，醒来手腕抬不起来。",
    illustrated: true,
    hotspotSize: 18,
    hotspots: [
      { id: "posterior-cord", label: "臂丛后束", detail: "桡神经是后束的直接延续，也是其最大的终末分支", position: [0.55, 1.69, 0.17], color: "#ee7c6a" },
      { id: "spiral-groove", label: "桡神经沟", detail: "在肱三头肌内、外侧头之间紧贴肱骨螺旋下行，肱骨干骨折时最易受累", position: [-0.07, 0.44, -0.13], color: "#f2a33b" },
      { id: "triceps", label: "肱三头肌", detail: "桡神经入沟前先发支支配三块伸肘肌，故沟处损伤仍可伸肘", position: [0.17, 0.74, -0.17], color: "#6393d8" },
      { id: "elbow-split", label: "肘外侧分支点", detail: "在肱骨外上髁前方分为浅支与深支", position: [-0.27, -0.02, -0.01], color: "#7fa88a" },
      { id: "posterior-interosseous", label: "骨间后神经", detail: "深支穿旋后肌进入前臂后区，支配全部前臂伸肌", position: [-0.31, -1.25, 0.07], color: "#d89bc4" },
      { id: "superficial-branch", label: "浅支（感觉支）", detail: "沿桡动脉外侧下行至手背，传递手背桡侧半感觉", position: [-0.64, -1.9, 0.36], color: "#b887a4" },
    ],
  },
  {
    id: "typical-vertebrae",
    name: "典型椎骨",
    scientificName: "Vertebrae typicae（C4、T7、L3）",
    system: "骨骼系统",
    model: "/models/typical-vertebrae.glb",
    icon: "≣",
    accent: "#a89f8a",
    description: "以第 4 颈椎、第 7 胸椎和第 3 腰椎为代表，展示三个节段椎骨的形态差异：颈椎轻巧并带横突孔，胸椎与肋骨相关节，腰椎椎体肥厚以承重。",
    poetic: "同一条脊柱上的三种设计",
    size: "颈椎最小，腰椎最大，胸椎介于其间",
    weight: "每块椎骨由椎体、椎弓和七个突起构成",
    location: "脊柱颈段、胸段和腰段",
    function: "承重、保护脊髓，并为肌肉和韧带提供附着",
    dailyFact: "椎动脉穿过颈椎横突孔上行入颅，转头时一侧孔道可轻度变窄",
    medical: "椎体压缩骨折多见于胸腰段；椎弓峡部裂则可引起腰椎滑脱。",
    bloodSupply: "节段性动脉（如肋间后动脉、腰动脉）发出的椎骨滋养支",
    funFact: "胸椎长棘突像叠瓦一样向下覆盖，因此背部正中摸到的骨节其实低于同名椎体。",
    illustrated: true,
    hotspots: [
      { id: "c4-foramen", label: "颈椎横突孔（C4）", detail: "横突上的圆孔，椎动脉与椎静脉由此上行入颅", position: [0.73, 1.56, 0.49], color: "#6393d8" },
      { id: "t7-facet", label: "胸椎肋凹（T7）", detail: "椎体与横突上的关节面，分别与肋骨头、肋结节相关节", position: [0.95, 0.35, -0.37], color: "#ee7c6a" },
      { id: "t7-spinous", label: "胸椎长棘突（T7）", detail: "细长棘突斜向后下方，呈叠瓦状排列", position: [0, -0.46, -0.7], color: "#f2a33b" },
      { id: "l3-body", label: "腰椎椎体（L3）", detail: "椎体短厚肥大，承担上半身重量", position: [0, -1.54, 1.07], color: "#7fa88a" },
      { id: "l3-spinous", label: "腰椎棘突（L3）", detail: "宽板状、水平后伸，是腰椎穿刺的重要体表标志", position: [0, -1.7, -1.07], color: "#d89bc4" },
    ],
  },
  {
    id: "lymphatic-system",
    name: "淋巴系统",
    scientificName: "Systema lymphoideum",
    system: "淋巴系统",
    model: "/models/lymphatic-system.glb",
    icon: "✦",
    accent: "#7fa86b",
    description: "遍布全身的淋巴器官与淋巴结网络：组织液经毛细淋巴管回收为淋巴，沿途由淋巴结过滤，最终经胸导管和右淋巴导管回流入血；模型展示头颈、胸腹、盆腔与四肢的主要淋巴结群，以及胸腺、脾和腭扁桃体。",
    poetic: "身体的过滤与警戒网络",
    size: "全身约有 600–700 枚淋巴结",
    weight: "随年龄与免疫状态变化，胸腺在青春期后逐渐退化",
    location: "从颈部、腋窝到纵隔、腹腔和腹股沟",
    function: "回收组织液、过滤淋巴并启动免疫应答",
    dailyFact: "每天约有 2–3 升淋巴液经淋巴系统回流到血液",
    medical: "感染或肿瘤转移时，引流区域的淋巴结会肿大；腋窝淋巴结清扫是乳腺癌分期的重要步骤。",
    bloodSupply: "淋巴道：毛细淋巴管 → 淋巴管 → 淋巴干 → 胸导管与右淋巴导管",
    funFact: "胸导管是全身最大的淋巴管，收集约四分之三身体的淋巴，最终注入左静脉角。",
    illustrated: true,
    hotspotSize: 16,
    hotspots: [
      { id: "tonsils", label: "腭扁桃体", detail: "咽淋巴环的一部分，是呼吸道入口的免疫前哨", position: [-0.1, 1.77, 0.08], color: "#d89bc4" },
      { id: "submandibular", label: "下颌下淋巴结", detail: "引流面部与口腔，头颈感染时常可触及", position: [-0.02, 1.58, 0.17], color: "#ee7c6a" },
      { id: "thymus", label: "胸腺（右叶）", detail: "T 淋巴细胞成熟的场所，青春期后逐渐脂肪化", position: [0.02, 1.02, 0.17], color: "#b98aa6" },
      { id: "axillary", label: "腋淋巴结", detail: "引流上肢与胸壁，乳腺癌转移首先关注这里", position: [-0.49, 0.94, -0.14], color: "#6393d8" },
      { id: "tracheobronchial", label: "气管支气管淋巴结", detail: "引流肺与纵隔，是胸部淋巴回流的枢纽", position: [0, 1.16, -0.05], color: "#f2a33b" },
      { id: "spleen", label: "脾", detail: "最大的淋巴器官，过滤血液并清除衰老红细胞", position: [0.29, 0.42, -0.03], color: "#b06a78" },
      { id: "mesenteric", label: "肠系膜淋巴结", detail: "肠道淋巴回流的中转站，肠道感染时可肿大疼痛", position: [0.01, -0.18, 0.18], color: "#7fa88a" },
      { id: "inguinal", label: "腹股沟浅淋巴结", detail: "引流下肢与会阴，下肢感染时常可触及肿大", position: [-0.21, -0.77, 0.15], color: "#c9956a" },
    ],
  },
  {
    id: "teeth",
    name: "牙齿（恒牙）",
    scientificName: "Dentes permanentes",
    system: "消化系统",
    model: "/models/teeth.glb",
    icon: "◭",
    accent: "#c8b78d",
    description: "上下牙弓共 28 颗恒牙（模型未含第三磨牙）：切牙切割、尖牙撕裂、前磨牙与磨牙研磨，是消化系统的第一道关口。",
    poetic: "咀嚼的第一道工序",
    size: "牙冠外露于牙龈，牙根埋于牙槽骨内",
    weight: "每颗牙由牙釉质、牙本质、牙骨质和牙髓构成",
    location: "上、下颌骨牙槽突的牙槽窝内",
    function: "切割、撕裂和研磨食物，并辅助发音",
    dailyFact: "第一磨牙约 6 岁萌出，俗称“六龄牙”，是不需要替换乳牙的恒牙",
    medical: "龋齿是最常见的口腔疾病；第一磨牙萌出早、窝沟深，是儿童龋坏的高发牙位。",
    bloodSupply: "上、下牙槽动脉（上颌动脉分支）",
    funFact: "牙釉质是全身最坚硬的组织，但一旦磨损或龋坏就无法自我修复。",
    illustrated: true,
    hotspotSize: 16,
    hotspots: [
      { id: "incisor", label: "上颌中切牙", detail: "铲状切缘用于切割食物", position: [-0.26, 0.56, 1.27], color: "#ee7c6a" },
      { id: "canine", label: "上颌尖牙", detail: "牙根最长，锥形牙尖用于撕裂", position: [-1.01, 0.75, 0.95], color: "#f2a33b" },
      { id: "premolar", label: "上颌第一前磨牙", detail: "双尖咬合面，辅助研磨", position: [-1.19, 0.76, 0.5], color: "#7fa88a" },
      { id: "upper-molar", label: "上颌第一磨牙", detail: "主要研磨牙，约 6 岁萌出的“六龄牙”", position: [-1.43, 0.83, -0.37], color: "#6393d8" },
      { id: "lower-molar", label: "下颌第一磨牙", detail: "咬合面窝沟深，是龋坏最好发的牙位之一", position: [-1.35, -0.39, -0.48], color: "#d89bc4" },
    ],
  },
  {
    id: "nose",
    name: "鼻",
    scientificName: "Nasus",
    system: "呼吸系统",
    model: "/models/nose.glb",
    icon: "◮",
    accent: "#91a9c8",
    description: "外鼻由鼻骨与鼻软骨共同支架，鼻腔内鼻甲卷曲突出；模型展示鼻骨、鼻中隔软骨、鼻外侧软骨与下鼻甲，呈现呼吸通道的骨与软骨框架。",
    poetic: "空气进入身体的第一站",
    size: "外鼻长约 5–6 厘米",
    weight: "由 2 块鼻骨、多块鼻软骨和成对鼻甲构成",
    location: "面部正中，口腔与眼眶之间",
    function: "加温、加湿、过滤吸入的空气，并容纳嗅觉感受器",
    dailyFact: "两侧鼻甲会每隔几小时交替充血，悄悄轮换“值班”",
    medical: "鼻骨是面部最常见的骨折部位；鼻中隔前下方的 Little 区是鼻出血最好发的位置。",
    bloodSupply: "筛前、筛后动脉（眼动脉）与蝶腭动脉（上颌动脉）分支",
    funFact: "鼻腔每天大约处理 1 万升空气，鼻毛和黏液会拦下其中大部分颗粒。",
    illustrated: true,
    hotspots: [
      { id: "nasal-bone", label: "鼻骨", detail: "成对的小骨构成鼻梁上段支架，是面部最常见的骨折部位", position: [-0.21, 0.57, 0.58], color: "#ee7c6a" },
      { id: "lateral-cartilage", label: "鼻外侧软骨", detail: "与鼻中隔软骨相连，决定鼻梁下段与鼻尖形态", position: [-0.33, -0.4, 1.04], color: "#6393d8" },
      { id: "septal-cartilage", label: "鼻中隔软骨", detail: "分隔左右鼻腔，前下方 Little 区是鼻出血好发处", position: [0, -0.5, 0.83], color: "#f2a33b" },
      { id: "inferior-concha", label: "下鼻甲", detail: "卷曲突入鼻腔，增大表面积以加温加湿空气", position: [-0.49, -0.75, -1.02], color: "#7fa88a" },
    ],
  },
];

export const organById = Object.fromEntries(organs.map((organ) => [organ.id, organ])) as Record<OrganId, Organ>;
