export type OrganId =
  | "heart"
  | "brain"
  | "lungs"
  | "liver"
  | "kidneys"
  | "eyeball"
  | "intestine"
  | "pancreas"
  | "skin"
  | "stomach"
  | "esophagus"
  | "spleen"
  | "gallbladder"
  | "bladder"
  | "trachea"
  | "appendix"
  | "tongue"
  | "ear"
  | "adrenal"
  | "diaphragm"
  | "thymus"
  | "spinal-cord"
  | "uterus"
  | "ovary"
  | "prostate"
  | "ureter";

export type Hotspot = {
  id: string;
  label: string;
  detail: string;
  position: [number, number, number];
  color: string;
};

export type Organ = {
  id: OrganId;
  name: string;
  scientificName: string;
  system: string;
  model: string;
  icon: string;
  accent: string;
  description: string;
  poetic: string;
  size: string;
  weight: string;
  location: string;
  function: string;
  dailyFact: string;
  medical: string;
  bloodSupply: string;
  /** A single memorable line, surfaced as the "Did you know" note. */
  funFact: string;
  hotspots: Hotspot[];
  /** Whether `/anatomy/<id>/*.webp` illustrations exist. Organs without them
   *  fall back to the accent glyph rather than a broken image. */
  illustrated: boolean;
};

export const organs: Organ[] = [
  {
    id: "heart",
    name: "心脏",
    scientificName: "Cor",
    system: "心血管系统",
    model: "/models/heart.glb",
    icon: "♥",
    accent: "#ee7c6a",
    description: "一个肌性器官，推动血液流遍全身，为每个细胞输送氧气和营养。",
    poetic: "不知疲倦的泵",
    size: "约等于你自己的拳头",
    weight: "250–350 克",
    location: "胸骨后方，略偏左",
    function: "推动含氧血液循环",
    dailyFact: "每天跳动约 10 万次",
    medical: "它的电节律协调着每一次心跳。",
    bloodSupply: "左、右冠状动脉",
    funFact: "人的一生中它约跳动 25 亿次，而且在出生之前就已经开始跳动。",
    illustrated: true,
    hotspots: [
      { id: "aorta", label: "主动脉", detail: "全身最大的动脉", position: [-0.35, 1.65, 0.55], color: "#ee7c6a" },
      { id: "left-atrium", label: "左心房", detail: "接收含氧血液", position: [0.82, 0.65, 0.5], color: "#f2a33b" },
      { id: "right-atrium", label: "右心房", detail: "接收静脉血", position: [-0.9, 0.35, 0.55], color: "#6393d8" },
      { id: "left-ventricle", label: "左心室", detail: "将血液泵向全身", position: [0.7, -0.75, 0.65], color: "#f2a33b" },
      { id: "right-ventricle", label: "右心室", detail: "将血液泵向肺部", position: [-0.65, -0.68, 0.66], color: "#ee7c6a" },
      { id: "mitral", label: "二尖瓣", detail: "防止血液回流", position: [0.18, -1.35, 0.48], color: "#d89bc4" },
    ],
  },
  {
    id: "brain",
    name: "大脑",
    scientificName: "Encephalon",
    system: "神经系统",
    model: "/models/brain.glb",
    icon: "◉",
    accent: "#c58696",
    description: "人体的指挥中心，整合感觉、记忆、情绪与精确的运动。",
    poetic: "内在宇宙",
    size: "约等于两只紧握的拳头",
    weight: "1.3–1.4 千克",
    location: "受颅骨保护",
    function: "处理并协调信号",
    dailyFact: "消耗全身约 20% 的能量",
    medical: "数十亿神经元通过电信号与化学信号相互通信。",
    bloodSupply: "颈内动脉与椎动脉",
    funFact: "大脑本身没有痛觉感受器——头痛其实来自它周围的组织。",
    illustrated: true,
    hotspots: [
      { id: "frontal", label: "额叶", detail: "计划与运动", position: [-0.7, 0.65, 0.8], color: "#ee7c6a" },
      { id: "parietal", label: "顶叶", detail: "感觉整合", position: [0.15, 1.1, 0.65], color: "#f2a33b" },
      { id: "temporal", label: "颞叶", detail: "记忆与听觉", position: [0.75, -0.1, 0.82], color: "#6393d8" },
      { id: "cerebellum", label: "小脑", detail: "平衡与协调", position: [0.72, -0.9, 0.55], color: "#d89bc4" },
    ],
  },
  {
    id: "lungs",
    name: "肺",
    scientificName: "Pulmones",
    system: "呼吸系统",
    model: "/models/lungs.glb",
    icon: "◍",
    accent: "#dd8f8b",
    description: "成对的器官，吸入空气，在广阔而脆弱的表面上以氧气交换二氧化碳。",
    poetic: "生命的气息",
    size: "每侧约 25 厘米高",
    weight: "双肺共约 1 千克",
    location: "心脏两侧，胸腔之内",
    function: "以氧气交换二氧化碳",
    dailyFact: "每天通气约 11,000 升",
    medical: "肺泡把相当于一个网球场大小的交换表面折叠进胸腔。",
    bloodSupply: "肺动脉与支气管动脉",
    funFact: "右肺有三叶，左肺只有两叶——为心脏留出了位置。",
    illustrated: true,
    hotspots: [
      { id: "trachea", label: "气管", detail: "将空气输送入肺", position: [0, 1.6, 0.2], color: "#6393d8" },
      { id: "right-lung", label: "右肺", detail: "分为三叶", position: [-1.2, 0.1, 0.7], color: "#ee7c6a" },
      { id: "left-lung", label: "左肺", detail: "两叶，为心脏留出空间", position: [1.2, 0.1, 0.7], color: "#f2a33b" },
      { id: "bronchus", label: "支气管", detail: "分支状气道", position: [-0.03, 0.3, 0.35], color: "#d89bc4" },
      { id: "base", label: "肺底", detail: "坐落在膈肌上", position: [-1.14, -1.2, 1], color: "#7fa88a" },
    ],
  },
  {
    id: "liver",
    name: "肝脏",
    scientificName: "Hepar",
    system: "消化系统",
    model: "/models/liver.glb",
    icon: "≈",
    accent: "#b86858",
    description: "卓越的代谢器官，过滤血液、处理营养物质并生成胆汁。",
    poetic: "沉默的炼金术士",
    size: "约一个橄榄球大小",
    weight: "1.4–1.6 千克",
    location: "右上腹",
    function: "代谢、解毒与分泌胆汁",
    dailyFact: "执行 500 多种功能",
    medical: "失去大量组织后仍能再生。",
    bloodSupply: "肝动脉与门静脉",
    funFact: "它是唯一能从一小部分组织再生回完整大小的人体器官。",
    illustrated: true,
    hotspots: [
      { id: "right-lobe", label: "右叶", detail: "最大的肝叶", position: [-0.75, 0.35, 0.75], color: "#ee7c6a" },
      { id: "left-lobe", label: "左叶", detail: "跨越中线", position: [0.85, 0.25, 0.75], color: "#f2a33b" },
      { id: "portal", label: "门静脉", detail: "富含营养的入肝血流", position: [0.1, -0.3, 0.82], color: "#6393d8" },
    ],
  },
  {
    id: "kidneys",
    name: "肾脏",
    scientificName: "Renes",
    system: "泌尿系统",
    model: "/models/kidneys.glb",
    icon: "∞",
    accent: "#c96963",
    description: "成对的过滤器官，维持体液、电解质与血压的平衡，并清除代谢废物。",
    poetic: "大师级过滤器",
    size: "每个约一只鼠标大小",
    weight: "每个 120–170 克",
    location: "脊柱两侧、肋骨下方",
    function: "过滤血液并生成尿液",
    dailyFact: "每天过滤约 180 升液体",
    medical: "肾单位精细调节血液的化学成分。",
    bloodSupply: "肾动脉",
    funFact: "过滤出的物质几乎都会被重吸收——最终只有约 1–2 升以尿液排出体外。",
    illustrated: true,
    hotspots: [
      { id: "cortex", label: "肾皮质", detail: "外层过滤结构", position: [-0.9, 0.55, 0.7], color: "#ee7c6a" },
      { id: "medulla", label: "肾髓质", detail: "浓缩尿液", position: [0.85, 0.2, 0.7], color: "#f2a33b" },
      { id: "ureter", label: "输尿管", detail: "输送尿液", position: [0.4, -1.1, 0.5], color: "#6393d8" },
    ],
  },
  {
    id: "eyeball",
    name: "眼",
    scientificName: "Oculus",
    system: "感觉系统",
    model: "/models/eyeball.glb",
    icon: "⊙",
    accent: "#7294b9",
    description: "精密的感觉器官，将聚焦的光线转化为神经信号，被大脑解读为视觉。",
    poetic: "一扇由光构成的窗",
    size: "直径约 24 毫米",
    weight: "约 7.5 克",
    location: "骨性眼眶之内",
    function: "捕捉并聚焦光线",
    dailyFact: "每天进行数千次微小运动",
    medical: "视网膜是中枢神经系统的延伸。",
    bloodSupply: "眼动脉",
    funFact: "角膜完全不含血管，直接从空气中获取氧气。",
    illustrated: true,
    hotspots: [
      { id: "cornea", label: "角膜", detail: "透明的聚焦表面", position: [-0.94, 0.05, 1.47], color: "#6393d8" },
      { id: "iris", label: "虹膜", detail: "控制进光量", position: [-1.22, -0.53, 1.15], color: "#f2a33b" },
      { id: "optic", label: "视神经", detail: "传递视觉信号", position: [1.61, -0.18, 0.54], color: "#d89bc4" },
    ],
  },
  {
    id: "intestine",
    name: "肠道",
    scientificName: "Intestinum",
    system: "消化系统",
    model: "/models/intestine.glb",
    icon: "§",
    accent: "#d78b77",
    description: "曲折盘绕的消化管道，营养在此吸收，肠道菌群支持着全身健康。",
    poetic: "内在花园",
    size: "完全展开约 6–7 米",
    weight: "随内容物而变化",
    location: "腹部中下部",
    function: "消化与营养吸收",
    dailyFact: "栖息着数万亿微生物",
    medical: "它的表面积被皱襞、绒毛和微绒毛逐级放大。",
    bloodSupply: "肠系膜上、下动脉",
    funFact: "肠内壁每隔几天就自我更新一次——是全身更新最快的组织。",
    illustrated: true,
    hotspots: [
      { id: "duodenum", label: "十二指肠", detail: "小肠的第一段", position: [0.6, 0.8, 0.75], color: "#f2a33b" },
      { id: "jejunum", label: "空肠", detail: "主要的吸收区域", position: [-0.45, 0.1, 0.82], color: "#ee7c6a" },
      { id: "colon", label: "结肠", detail: "重吸收水分", position: [0.75, -0.55, 0.72], color: "#6393d8" },
    ],
  },
  {
    id: "pancreas",
    name: "胰腺",
    scientificName: "Pancreas",
    system: "内分泌系统",
    model: "/models/pancreas.glb",
    icon: "◈",
    accent: "#c69a5e",
    description: "一腺两用：向肠道释放消化酶，同时分泌稳定血糖的激素。",
    poetic: "安静的调节者",
    size: "长约 15 厘米",
    weight: "70–100 克",
    location: "胃的后方，横过上腹部",
    function: "分泌消化酶与胰岛素",
    dailyFact: "每天产生约 1.5 升富含酶的胰液",
    medical: "胰岛释放胰岛素和胰高血糖素，维持血糖平衡。",
    bloodSupply: "脾动脉与胰十二指肠动脉",
    funFact: "只有约 2% 的组织负责分泌激素，其余都用于制造消化酶。",
    illustrated: true,
    hotspots: [
      { id: "head", label: "胰头", detail: "被十二指肠环抱", position: [-1.32, -0.36, 0.55], color: "#ee7c6a" },
      { id: "body", label: "胰体", detail: "横跨脊柱", position: [0.05, 0.25, 0.45], color: "#f2a33b" },
      { id: "tail", label: "胰尾", detail: "延伸至脾脏", position: [1.55, 0.3, 0.35], color: "#6393d8" },
      { id: "duct", label: "胰管", detail: "将消化酶排入肠道", position: [-0.61, 0.39, 0.5], color: "#d89bc4" },
    ],
  },
  {
    id: "skin",
    name: "皮肤",
    scientificName: "Integumentum",
    system: "体被系统",
    model: "/models/skin.glb",
    icon: "▦",
    accent: "#c99277",
    description: "人体最大的器官——一道活的屏障，感知触觉、锁住水分并调节体温。",
    poetic: "活的边界",
    size: "摊平约 2 平方米",
    weight: "3.5–5 千克",
    location: "覆盖全身",
    function: "保护、感知与散热",
    dailyFact: "每天脱落约 5 亿个细胞",
    medical: "表皮、真皮、皮下组织三层各有分工。",
    bloodSupply: "真皮血管丛",
    funFact: "一平方厘米的皮肤可容纳数百个汗腺和数米长的血管。",
    illustrated: true,
    hotspots: [
      { id: "epidermis", label: "表皮", detail: "外部的保护层", position: [-0.05, 0.88, 1.4], color: "#ee7c6a" },
      { id: "dermis", label: "真皮", detail: "神经、血管与腺体所在", position: [0.29, 0.05, 1.4], color: "#f2a33b" },
      { id: "hypodermis", label: "皮下组织", detail: "脂肪与保温层", position: [-0.39, -1.15, 1.4], color: "#6393d8" },
      { id: "follicle", label: "毛囊", detail: "固定每根毛发", position: [0.89, -0.44, 1.4], color: "#d89bc4" },
    ],
  },
  {
    id: "stomach",
    name: "胃",
    scientificName: "Gaster",
    system: "消化系统",
    model: "/models/stomach.glb",
    icon: "∪",
    accent: "#dd8a72",
    description: "J 形的肌性囊袋，通过蠕动、胃酸与消化酶把食物搅拌成食糜，再分批送入小肠。",
    poetic: "消化的熔炉",
    size: "完全舒张时长约 25 厘米",
    weight: "空腹时约 150–200 克",
    location: "左上腹，肋弓下方",
    function: "储存并初步消化食物",
    dailyFact: "分泌约 1.5–2 升胃液",
    medical: "胃黏膜每 3–4 天更新一次，以免被自身胃酸侵蚀。",
    bloodSupply: "胃左、胃右与胃网膜动脉",
    funFact: "胃酸的 pH 可低至 1.5–2.0——足以溶解锌，却伤不到胃壁本身。",
    illustrated: false,
    hotspots: [
      { id: "cardia", label: "贲门", detail: "连接食管，防止反流", position: [0.5, 1.1, 0.6], color: "#6393d8" },
      { id: "fundus", label: "胃底", detail: "食物与气体的暂存区", position: [1.25, 0.85, 0.5], color: "#f2a33b" },
      { id: "body", label: "胃体", detail: "研磨与消化的主区域", position: [0, 0, 1.5], color: "#ee7c6a" },
      { id: "pylorus", label: "幽门", detail: "控制食糜进入十二指肠", position: [-1.25, -1.0, 0.7], color: "#d89bc4" },
    ],
  },
  {
    id: "esophagus",
    name: "食管",
    scientificName: "Oesophagus",
    system: "消化系统",
    model: "/models/esophagus.glb",
    icon: "∥",
    accent: "#d9a98c",
    description: "一条长约 25 厘米的肌性管道，通过蠕动波把食团从咽部一路推送进胃。",
    poetic: "食物的滑道",
    size: "长约 25 厘米，直径约 2 厘米",
    weight: "薄壁肌性管道",
    location: "咽部与胃之间，穿行胸腔",
    function: "蠕动输送食团",
    dailyFact: "配合每天上千次吞咽",
    medical: "下食管括约肌防止胃酸反流入胸腔。",
    bloodSupply: "甲状腺下动脉与胃左动脉分支",
    funFact: "食团靠蠕动推进，不靠重力——倒立时也能正常喝水。",
    illustrated: false,
    hotspots: [
      { id: "cervical", label: "颈段", detail: "起自咽部", position: [0, 1.5, 0.25], color: "#6393d8" },
      { id: "thoracic", label: "胸段", detail: "穿行于心脏后方", position: [0, 0, 0.3], color: "#f2a33b" },
      { id: "junction", label: "食管胃连接部", detail: "穿过膈肌进入胃", position: [0.15, -1.8, 0.3], color: "#ee7c6a" },
    ],
  },
  {
    id: "spleen",
    name: "脾",
    scientificName: "Splen",
    system: "淋巴系统",
    model: "/models/spleen.glb",
    icon: "◑",
    accent: "#b06a78",
    description: "人体最大的淋巴器官，过滤血液、清除衰老血细胞，并储存免疫细胞与血小板。",
    poetic: "血液的净化站",
    size: "约一个拳头大小，长约 11 厘米",
    weight: "约 150 克",
    location: "左上腹，第 9–11 肋深面",
    function: "过滤血液并参与免疫",
    dailyFact: "储存全身约 1/3 的血小板",
    medical: "位置贴近肋骨，外伤时是腹腔内最易破裂的器官。",
    bloodSupply: "脾动脉与脾静脉",
    funFact: "被切除后人依然可以存活——肝脏和骨髓会接管它的大部分工作。",
    illustrated: false,
    hotspots: [
      { id: "upper-pole", label: "上极", detail: "朝向膈肌", position: [0.3, 1.7, 0.8], color: "#f2a33b" },
      { id: "hilum", label: "脾门", detail: "血管与淋巴管出入处", position: [0.33, -0.14, 0.9], color: "#ee7c6a" },
      { id: "lower-pole", label: "下极", detail: "靠近左肾与结肠", position: [1.23, -1.85, 0.5], color: "#6393d8" },
    ],
  },
  {
    id: "gallbladder",
    name: "胆囊",
    scientificName: "Vesica biliaris",
    system: "消化系统",
    model: "/models/gallbladder.glb",
    icon: "❍",
    accent: "#7fa88a",
    description: "藏在肝脏下方的梨形囊袋，浓缩并储存胆汁，进食脂肪时将其排入十二指肠。",
    poetic: "胆汁的仓库",
    size: "长约 7–10 厘米",
    weight: "可储存约 50 毫升胆汁",
    location: "右上腹，肝脏下面",
    function: "浓缩、储存与排放胆汁",
    dailyFact: "肝脏每天分泌约 800–1000 毫升胆汁",
    medical: "胆固醇过饱和时容易在囊内形成结石。",
    bloodSupply: "胆囊动脉（多源自肝右动脉）",
    funFact: "它能把肝脏送来的胆汁浓缩到原来的十分之一。",
    illustrated: false,
    hotspots: [
      { id: "gb-fundus", label: "胆囊底", detail: "圆钝突出的下端", position: [-0.15, -1.8, -0.3], color: "#f2a33b" },
      { id: "gb-body", label: "胆囊体", detail: "储存胆汁的主体", position: [0.2, 0, 1.0], color: "#ee7c6a" },
      { id: "gb-neck", label: "胆囊颈", detail: "连接胆囊管", position: [0.4, 1.7, 0.3], color: "#6393d8" },
    ],
  },
  {
    id: "bladder",
    name: "膀胱",
    scientificName: "Vesica urinaria",
    system: "泌尿系统",
    model: "/models/bladder.glb",
    icon: "▽",
    accent: "#c9a25e",
    description: "富有弹性的肌性储尿囊，充盈时升入腹腔，排空后缩回盆腔。",
    poetic: "身体的蓄水池",
    size: "容量约 400–500 毫升",
    weight: "空虚时约 50 克",
    location: "盆腔前部，耻骨联合后方",
    function: "储存并排出尿液",
    dailyFact: "每天排尿约 4–8 次",
    medical: "尿液达到约 150–250 毫升时便会产生尿意。",
    bloodSupply: "膀胱上、下动脉",
    funFact: "它的内壁布满皱襞，充盈时会被撑平——容积可扩大近十倍。",
    illustrated: false,
    hotspots: [
      { id: "dome", label: "膀胱穹窿", detail: "充盈时升高的顶部", position: [0, 0.6, 1.5], color: "#f2a33b" },
      { id: "trigone", label: "膀胱三角", detail: "两输尿管口与尿道内口之间", position: [0.15, -0.1, -1.44], color: "#6393d8" },
      { id: "ureteric", label: "输尿管口", detail: "输尿管进入膀胱处", position: [1.38, 0.56, -1.52], color: "#d89bc4" },
      { id: "neck", label: "膀胱颈", detail: "连接尿道", position: [0.2, -1.0, -0.5], color: "#ee7c6a" },
    ],
  },
  {
    id: "trachea",
    name: "气管",
    scientificName: "Trachea",
    system: "呼吸系统",
    model: "/models/trachea.glb",
    icon: "⋮",
    accent: "#cf9d90",
    description: "由 C 形软骨环支撑的通气管道，把空气导入支气管，同时加温、湿润并清扫它。",
    poetic: "空气的长廊",
    size: "长约 10–12 厘米",
    weight: "由 16–20 个软骨环支撑",
    location: "颈部正中至胸腔，约第 4–5 胸椎处分叉",
    function: "通气并清洁吸入的空气",
    dailyFact: "内壁纤毛不停向上清扫黏液",
    medical: "异物误吸多落入右侧主支气管——它更粗、更直。",
    bloodSupply: "甲状腺下动脉与支气管动脉",
    funFact: "C 形软骨环的缺口朝后，给身后的食管留出吞咽扩张的空间。",
    illustrated: false,
    hotspots: [
      { id: "cricoid", label: "环状软骨", detail: "气管的起始支架", position: [0, 1.7, 0.3], color: "#6393d8" },
      { id: "rings", label: "气管软骨环", detail: "保持气道持续开放", position: [-0.2, 0, 0.55], color: "#f2a33b" },
      { id: "carina", label: "气管杈", detail: "分为左、右主支气管", position: [0, -1.8, 0.2], color: "#ee7c6a" },
    ],
  },
  {
    id: "appendix",
    name: "阑尾",
    scientificName: "Appendix vermiformis",
    system: "消化系统",
    model: "/models/appendix.glb",
    icon: "∿",
    accent: "#dda086",
    description: "盲肠末端伸出的一条细管，是肠道有益菌群躲避风雨的“安全屋”。",
    poetic: "肠道菌的避难所",
    size: "长约 6–9 厘米",
    weight: "细如蚯蚓，仅数克",
    location: "右下腹，盲肠末端",
    function: "储存有益的肠道菌群",
    dailyFact: "管腔极细，容易被粪石堵塞",
    medical: "阑尾炎发作时需及时处理，穿孔可致腹膜炎。",
    bloodSupply: "阑尾动脉（回结肠动脉分支）",
    funFact: "它曾被认为是退化无用的器官，如今被视为肠道菌群的后备仓库。",
    illustrated: false,
    hotspots: [
      { id: "base", label: "阑尾根部", detail: "连接盲肠", position: [1.5, -0.2, 0.4], color: "#f2a33b" },
      { id: "shaft", label: "阑尾体", detail: "细长的盲管", position: [0, 0, 0.9], color: "#ee7c6a" },
      { id: "tip", label: "阑尾尖", detail: "游离的末端", position: [-1.6, 0.4, 0.6], color: "#6393d8" },
    ],
  },
  {
    id: "tongue",
    name: "舌",
    scientificName: "Lingua",
    system: "消化系统",
    model: "/models/tongue.glb",
    icon: "∽",
    accent: "#d9796a",
    description: "由八块肌肉交织而成的灵活器官，搅拌食物、感受味道并协助发音。",
    poetic: "味道的舞台",
    size: "长约 8–10 厘米",
    weight: "由 8 块肌肉交织而成",
    location: "口腔之内",
    function: "搅拌食物、味觉与发音",
    dailyFact: "分布着约 2,000–4,000 个味蕾",
    medical: "味蕾每 10–14 天就会更新一轮。",
    bloodSupply: "舌动脉（颈外动脉分支）",
    funFact: "“味觉分区图”是讹传——舌头的各个区域都能尝出五种基本味道。",
    illustrated: false,
    hotspots: [
      { id: "tip", label: "舌尖", detail: "最灵活的部分", position: [0.2, 0.5, 1.7], color: "#ee7c6a" },
      { id: "body", label: "舌体", detail: "味蕾密布的区域", position: [0, 0.3, 0.8], color: "#f2a33b" },
      { id: "root", label: "舌根", detail: "连接会厌与咽部", position: [0.3, -0.5, -1.3], color: "#6393d8" },
    ],
  },
  {
    id: "ear",
    name: "耳",
    scientificName: "Auris externa",
    system: "感觉系统",
    model: "/models/ear.glb",
    icon: "◖",
    accent: "#d4a184",
    description: "耳廓收集声波并导入耳道，经鼓膜与听小骨接力，最终转化为神经信号。",
    poetic: "声音的收集器",
    size: "耳廓高约 6 厘米",
    weight: "仅数克重",
    location: "头部两侧",
    function: "收集并传导声波",
    dailyFact: "双耳靠时间差分辨声源方向",
    medical: "鼓膜只有约 0.1 毫米厚，却能高效传递振动。",
    bloodSupply: "耳后动脉与颞浅动脉",
    funFact: "人的耳朵一辈子都在缓慢长大——软骨会持续生长。",
    illustrated: false,
    hotspots: [
      { id: "helix", label: "耳轮", detail: "耳廓外缘的卷曲", position: [0.3, 1.4, 0.5], color: "#f2a33b" },
      { id: "concha", label: "耳甲", detail: "声波汇集的凹陷", position: [-0.2, 0, 0.9], color: "#ee7c6a" },
      { id: "lobule", label: "耳垂", detail: "没有软骨的柔软末端", position: [-0.5, -1.5, 0.9], color: "#6393d8" },
    ],
  },
  {
    id: "adrenal",
    name: "肾上腺",
    scientificName: "Glandula suprarenalis",
    system: "内分泌系统",
    model: "/models/adrenal.glb",
    icon: "▲",
    accent: "#bf9b52",
    description: "骑在两侧肾上极的小腺体，外层分泌皮质激素，核心分泌肾上腺素。",
    poetic: "应激的开关",
    size: "骑在肾上极的小三角帽",
    weight: "每个仅约 4–5 克",
    location: "两侧肾脏上方",
    function: "分泌肾上腺素与皮质激素",
    dailyFact: "应激时几秒内心率和血压上升",
    medical: "皮质分泌皮质醇，髓质分泌肾上腺素，各司其职。",
    bloodSupply: "肾上腺上、中、下三组动脉",
    funFact: "名字相当直白——“肾上腺”就是“长在肾上面的腺体”。",
    illustrated: false,
    hotspots: [
      { id: "left", label: "左肾上腺", detail: "半月形，贴左肾上极", position: [-1.36, -0.23, 0.5], color: "#f2a33b" },
      { id: "right", label: "右肾上腺", detail: "三角形，贴右肾上极", position: [1.16, 0.32, 0.4], color: "#6393d8" },
      { id: "medulla", label: "肾上腺髓质", detail: "分泌肾上腺素", position: [-1.3, 0.3, 0.3], color: "#ee7c6a" },
    ],
  },
  {
    id: "diaphragm",
    name: "膈肌",
    scientificName: "Diaphragma",
    system: "呼吸系统",
    model: "/models/diaphragm.glb",
    icon: "◠",
    accent: "#bd7f6e",
    description: "隔开胸腔与腹腔的穹窿状肌肉，它的收缩舒张驱动每一次呼吸。",
    poetic: "呼吸的引擎",
    size: "穹窿状，厚仅数毫米",
    weight: "最重要的呼吸肌",
    location: "胸腔与腹腔之间",
    function: "收缩产生吸气",
    dailyFact: "每天随呼吸运动约 2 万次",
    medical: "打嗝就是膈肌不自主的痉挛。",
    bloodSupply: "膈上、膈下动脉",
    funFact: "咳嗽、呕吐和排便时的腹压，也都有它参与。",
    illustrated: false,
    hotspots: [
      { id: "central-tendon", label: "中心腱", detail: "穹窿顶部的腱膜", position: [0, 1.2, 0.9], color: "#f2a33b" },
      { id: "caval", label: "腔静脉孔", detail: "下腔静脉穿过处", position: [0.7, 0.5, 0.8], color: "#6393d8" },
      { id: "esophageal", label: "食管裂孔", detail: "食管穿过处", position: [-0.3, 0.1, 0.7], color: "#ee7c6a" },
      { id: "aortic", label: "主动脉裂孔", detail: "主动脉穿过处", position: [-0.2, -0.9, -0.6], color: "#d89bc4" },
    ],
  },
  {
    id: "thymus",
    name: "胸腺",
    scientificName: "Thymus",
    system: "淋巴系统",
    model: "/models/thymus.glb",
    icon: "❋",
    accent: "#b98aa6",
    description: "位于胸骨后方的免疫“学校”，T 淋巴细胞在这里学习识别敌我。",
    poetic: "免疫的学校",
    size: "青春期时最大",
    weight: "青春期约 30–40 克",
    location: "胸骨后方，心脏上方",
    function: "培育成熟的 T 淋巴细胞",
    dailyFact: "青春期后逐渐脂肪化",
    medical: "重症肌无力常与胸腺异常相关。",
    bloodSupply: "胸廓内动脉分支",
    funFact: "它会随年龄“退休”——成年后大部分被脂肪组织替代。",
    illustrated: false,
    hotspots: [
      { id: "left-lobe", label: "左叶", detail: "胸腺的两个叶之一", position: [-0.5, 0.2, 0.5], color: "#f2a33b" },
      { id: "right-lobe", label: "右叶", detail: "两叶在中线会合", position: [0.4, 0.1, 0.6], color: "#6393d8" },
    ],
  },
  {
    id: "spinal-cord",
    name: "脊髓",
    scientificName: "Medulla spinalis",
    system: "神经系统",
    model: "/models/spinal-cord.glb",
    icon: "┃",
    accent: "#a08fc4",
    description: "大脑与身体之间的信息高速公路，藏于椎管之内，还能独立完成反射。",
    poetic: "信息的高速公路",
    size: "长约 42–45 厘米",
    weight: "约 30–35 克",
    location: "椎管内，枕骨大孔至第 1–2 腰椎",
    function: "传递神经信号并完成反射",
    dailyFact: "每秒传递数以百万计的信号",
    medical: "损伤平面以下的感觉与运动功能会受损。",
    bloodSupply: "脊髓前、后动脉",
    funFact: "膝跳反射不经过大脑——脊髓自己就能完成整个反射弧。",
    illustrated: false,
    hotspots: [
      { id: "cervical", label: "颈段", detail: "支配上肢的膨大区", position: [0, 1.5, 0.4], color: "#6393d8" },
      { id: "thoracic", label: "胸段", detail: "最长的一段", position: [-0.05, 0.1, 0.2], color: "#f2a33b" },
      { id: "lumbosacral", label: "腰骶段", detail: "末端延续为马尾", position: [0.05, -1.6, 0.2], color: "#ee7c6a" },
    ],
  },
  {
    id: "uterus",
    name: "子宫",
    scientificName: "Uterus",
    system: "生殖系统",
    model: "/models/uterus.glb",
    icon: "◡",
    accent: "#cf7f8f",
    description: "梨形的肌性器官，内膜每月周期性更新，受孕后孕育胎儿直至分娩。",
    poetic: "生命的摇篮",
    size: "未孕时长约 7–8 厘米",
    weight: "约 50–70 克",
    location: "盆腔中央，膀胱与直肠之间",
    function: "孕育胎儿并产生月经",
    dailyFact: "孕期可增大数十倍",
    medical: "子宫内膜每月周期性增生与脱落。",
    bloodSupply: "子宫动脉（髂内动脉分支）",
    funFact: "怀孕时，它能从梨子大小扩张到西瓜大小。",
    illustrated: false,
    hotspots: [
      { id: "fundus", label: "子宫底", detail: "输卵管入口以上的顶部", position: [0.13, 0.79, 1.2], color: "#f2a33b" },
      { id: "body", label: "子宫体", detail: "胎儿发育的场所", position: [0.12, 0.37, 0.6], color: "#ee7c6a" },
      { id: "cervix", label: "子宫颈", detail: "通向阴道的门户", position: [0.15, -0.54, -1.22], color: "#6393d8" },
      { id: "tube", label: "输卵管口", detail: "输卵管进入子宫处", position: [-0.19, 0.79, 1.03], color: "#d89bc4" },
    ],
  },
  {
    id: "ovary",
    name: "卵巢",
    scientificName: "Ovarium",
    system: "生殖系统",
    model: "/models/ovary.glb",
    icon: "◐",
    accent: "#c9879b",
    description: "杏仁大小的腺体，储存卵泡、周期性排卵，并分泌雌激素与孕激素。",
    poetic: "卵子的宝库",
    size: "长约 3–4 厘米，如杏仁",
    weight: "约 5–6 克",
    location: "盆腔内，子宫两侧",
    function: "排卵并分泌性激素",
    dailyFact: "卵泡储备在出生前就已备好",
    medical: "多囊卵巢是常见的内分泌紊乱。",
    bloodSupply: "卵巢动脉（腹主动脉分支）",
    funFact: "出生时卵巢里有一两百万个卵泡，到青春期只剩约 30 万个。",
    illustrated: false,
    hotspots: [
      { id: "cortex", label: "卵巢皮质", detail: "卵泡所在的区域", position: [0.3, 0.4, 0.9], color: "#ee7c6a" },
      { id: "hilum", label: "卵巢门", detail: "血管与神经出入处", position: [-0.4, -0.4, 0.4], color: "#6393d8" },
    ],
  },
  {
    id: "prostate",
    name: "前列腺",
    scientificName: "Prostata",
    system: "生殖系统",
    model: "/models/prostate.glb",
    icon: "❖",
    accent: "#9b86b8",
    description: "倒扣在膀胱出口的栗子形腺体，分泌的液体是精液的主要成分。",
    poetic: "膀胱的守门人",
    size: "栗子大小，约 3–4 厘米",
    weight: "约 20 克",
    location: "膀胱下方，包绕尿道起始部",
    function: "分泌前列腺液",
    dailyFact: "随年龄增长容易增生变大",
    medical: "增生后压迫尿道，导致排尿困难。",
    bloodSupply: "膀胱下动脉分支",
    funFact: "尿道从它正中穿过——所以它一变大，排尿就先受影响。",
    illustrated: false,
    hotspots: [
      { id: "base", label: "前列腺底", detail: "紧贴膀胱颈", position: [-0.2, -0.6, 0.8], color: "#f2a33b" },
      { id: "apex", label: "前列腺尖", detail: "朝向尿生殖膈", position: [-0.16, -1.41, 0.5], color: "#6393d8" },
      { id: "seminal", label: "精囊", detail: "成对的分泌腺体", position: [-0.28, 0.45, -0.2], color: "#ee7c6a" },
      { id: "vas", label: "输精管", detail: "输送精子的管道", position: [-1.3, 1.11, -0.1], color: "#d89bc4" },
    ],
  },
  {
    id: "ureter",
    name: "输尿管",
    scientificName: "Ureter",
    system: "泌尿系统",
    model: "/models/ureter.glb",
    icon: "⋀",
    accent: "#c9956a",
    description: "连接肾盂与膀胱的细长肌性管道，靠一波波蠕动把尿液挤进膀胱。",
    poetic: "尿液的传送带",
    size: "长约 25–30 厘米，直径仅 3–4 毫米",
    weight: "细长的肌性管道",
    location: "肾盂与膀胱之间，贴后腹膜下行",
    function: "蠕动输送尿液",
    dailyFact: "每分钟蠕动数次推送尿液",
    medical: "结石常卡在它的三处生理性狭窄。",
    bloodSupply: "肾动脉与髂动脉的分支",
    funFact: "尿液不是靠重力下流，而是被管壁一波波挤进膀胱的。",
    illustrated: false,
    hotspots: [
      { id: "pelvis", label: "肾盂", detail: "收集肾脏生成的尿液", position: [0.73, 1.48, 0.3], color: "#f2a33b" },
      { id: "abdominal", label: "输尿管腹段", detail: "贴腰大肌下行", position: [0.4, -0.29, 0.5], color: "#ee7c6a" },
      { id: "intramural", label: "膀胱壁内段", detail: "斜穿膀胱壁防止反流", position: [0.2, -1.6, 0.3], color: "#6393d8" },
    ],
  },
];

export const organById = Object.fromEntries(organs.map((organ) => [organ.id, organ])) as Record<OrganId, Organ>;
